// Compiles the policy unit: potestas/potestas.gen.c (generated by Exsecutor's
// exsc, see potestas/PROVENANCE.md) and potestas/shim.c (its one import).
fn main() {
    println!("cargo:rerun-if-changed=potestas/potestas.gen.c");
    println!("cargo:rerun-if-changed=potestas/shim.c");
    cc::Build::new()
        .file("potestas/potestas.gen.c")
        .file("potestas/shim.c")
        .std("c11")
        // The emitted prologue refuses -ffast-math with an #error.
        .flag_if_supported("-fno-fast-math")
        // Every unit carries the whole helper set; unused ones are expected.
        .flag_if_supported("-Wno-unused-function")
        .compile("potestas");
}
