{ config, lib, pkgs, hydramesh, ... }:

with lib;

let
  cfg = config.custom.hydramesh;

  hm = hydramesh.packages.${pkgs.system} or
    (throw "the hydramesh flake has no packages for system ${pkgs.system}");

  # The generated DCF node config. modules/dcf-community-node.nix mounts an
  # equivalent TOML into the container; this is the host-visible copy the
  # `hydramesh` MCP aspect's `node_config` tool reads (read-only, sandboxed).
  configPath = "/etc/hydramesh/dcf_config.toml";
in
{
  ###########################################################################
  # HydraMesh — DeMoD Communication Framework SDK CLIs.
  #
  # NOTE ON THE DEFAULT: CLAUDE.md's convention is that custom.* features are
  # declared here and default to OFF, then flipped on in configuration.nix.
  # This module deliberately breaks that rule and defaults to ON, because
  # HydraMesh is a stated requirement of the distro rather than a feature:
  # the `hydramesh` MCP aspect and the `dcf` aspect's `mesh_peers` tool both
  # shell out to binaries that only exist because of this module. The ISO
  # force-disables it (see flake.nix) to keep the installer image light.
  ###########################################################################

  options.custom.hydramesh = {
    enable = mkOption {
      type = types.bool;
      default = true;
      description = ''
        Install the HydraMesh / DCF SDK command-line tools. Required by the
        `hydramesh` MCP aspect server and by `oligarchy-dcf-mcp`'s `mesh_peers`
        tool. Defaults to true — HydraMesh is a requirement of the distro.
      '';
    };

    withModemTools = mkOption {
      type = types.bool;
      default = true;
      description = ''
        Also install the HydraModem CLI toolbox (`hydramodem-tools`:
        `dcf_loopback`, `frame_tx`, `frame_rx`, `sense_node`, the tx/rx
        campaigns and the SSTV tools). The `hydramesh` MCP aspect only ever
        invokes `dcf_loopback`, and then only behind an explicit confirmation
        argument; the transmit-side tools are not on its allowlist.

        Note that the `hydramodem` package itself installs no binaries — it is
        the library (libhydramodem.so + headers + pkg-config file). Both are
        installed when this is true.
      '';
    };
  };

  config = mkIf cfg.enable {
    environment.systemPackages = [
      # Rust SDK node -> `dcf`. Read-only verbs: status, list-peers, metrics,
      # version, info (all emit pretty JSON).
      hm.dcf-rust
      # D-LISP SDK -> `hydramesh`. Read-only verbs: status, list-peers,
      # metrics, version, help, agent-list, agent-backends.
      hm.hydramesh-lisp
    ]
    ++ optionals cfg.withModemTools [
      # Library only (libhydramodem.so, headers, .pc) — installs no binaries.
      hm.hydramodem
      # The actual CLIs: dcf_loopback, frame_tx, frame_rx, sense_node,
      # tx_campaign, rx_campaign, sstv_send, sstv_recv, snake_loopback.
      hm.hydramodem-tools
    ];

    # Host-visible DCF node config. Mirrors the server/network blocks that
    # modules/dcf-community-node.nix generates for the container, so the
    # `hydramesh` MCP aspect can report the node's wire configuration without
    # needing docker or a running node.
    environment.etc."hydramesh/dcf_config.toml".text = ''
      # Generated by modules/hydramesh.nix — do not edit.
      # Read-only reference copy of the DCF node wire configuration.
      mode = "community"

      [server]
      bind_udp = "0.0.0.0:7777"     # HydraMesh binary protocol
      bind_grpc = "0.0.0.0:50051"   # gRPC management
      bind_shim = "0.0.0.0:8888"    # shim listener (Zandronum/legacy)

      [network]
      discovery_mode = "central"
      node_type = "community"
    '';

    # Consumed by oligarchy-hydramesh-mcp's `node_config` tool.
    environment.sessionVariables.OLIGARCHY_HYDRAMESH_CONFIG = configPath;
  };
}
