# custom.session — bring the Hyprland session back after a reboot.
#
# Defaults OFF. Flip it in ~/.config/oligarchy/local.nix (or configuration.nix),
# do not edit this file to "turn it on". Nothing is configured with
# `autoLogin.enable = false`, so the ISO needs no mkForce.
#
# Two halves, deliberately split:
#   autoLogin.*  — system level, configured HERE. greetd is a system daemon, so
#                  the "log straight into Hyprland" half cannot live in home/.
#   restore.*    — user level, only DECLARED here. The window save/restore units
#                  and the hyprlock exec-once are Home Manager's, and read these
#                  values back as `osConfig.custom.session or { }`. This module
#                  sets nothing for them; it owns the names, not the behaviour.
#
# What this does NOT do (security):
# - Does not replace `default_session`. tuigreet stays the default, so a
#   compositor crash or a plain logout lands on the greeter asking for a
#   password — it can never loop back around into another autologin.
# - Does not weaken the at-rest gate: LUKS whole-disk encryption is what
#   protects this machine powered off, and autologin does not touch it. The
#   threat autologin *does* add is someone walking up to a booted laptop, which
#   is why `lockOnLogin` defaults to true — hyprlock comes up before the desktop
#   is ever visible.
# - Does not set `services.greetd.restart`. See the comment at initial_session.
# - Does not enable anything by itself; every option here defaults off/safe, so
#   a fresh clone behaves exactly as it did before this file existed.
{ config
, lib
, pkgs
, ...
}:

let
  cfg = config.custom.session;
in
{
  options.custom.session = {
    autoLogin = {
      enable = lib.mkEnableOption ''
        automatic login straight into Hyprland on boot, via greetd's
        `initial_session`. `default_session` stays tuigreet, so this fires
        exactly once per greetd start: log out, or crash the compositor, and
        you get the password prompt instead of a second autologin.
        Requires `services.greetd.enable` and `programs.hyprland.enable`
      '';

      lockOnLogin = lib.mkOption {
        type = lib.types.bool;
        default = true;
        description = ''
          Start hyprlock as the first thing in the auto-logged-in session, so
          the desktop is never displayed unlocked.

          Consumed by Home Manager (`home/hyprland/`) via
          `osConfig.custom.session.autoLogin.lockOnLogin`, not by this module —
          the compositor's `exec-once` is user-level config.

          Defaults true on purpose: autologin's whole cost is that a booted
          machine no longer asks for anything, and this is what pays it back.
          Turning it off means a reboot leaves a live, unlocked desktop on tty1.
        '';
      };
    };

    restore = {
      enable = lib.mkOption {
        type = lib.types.bool;
        default = false;
        description = ''
          Save the open windows (class, workspace, geometry, argv, cwd) while a
          session runs and relaunch them when the next one starts.

          Declared here so a single `custom.session` block covers both halves of
          "come back after a reboot", but implemented entirely in Home Manager
          (`hypr-session` plus its user units); this module sets nothing for it.
          Reading it from home/ is `osConfig.custom.session.restore.enable`,
          guarded with `or { }` so a fresh clone that never imported this file
          still evaluates.
        '';
      };

      saveInterval = lib.mkOption {
        type = lib.types.str;
        default = "2min";
        example = "30s";
        description = ''
          How often the snapshot timer re-saves the window list, as a systemd
          timespan (`OnUnitActiveSec`).

          This is the real guarantee: a clean logout saves on the way out, but a
          crash or a power cut only leaves whatever the timer last wrote, so the
          worst-case loss is one interval. Consumed by Home Manager.
        '';
      };
    };
  };

  config = lib.mkIf cfg.autoLogin.enable {
    assertions = [
      {
        assertion = config.services.greetd.enable;
        message = ''
          custom.session.autoLogin.enable requires services.greetd.enable:
          autologin is implemented as greetd's `initial_session`, so with no
          greetd there is nothing to log in with and the option would silently
          do nothing.
        '';
      }
      {
        assertion = config.programs.hyprland.enable;
        message = ''
          custom.session.autoLogin.enable requires programs.hyprland.enable:
          the session command is `Hyprland`, which programs.hyprland puts on the
          login PATH. Without it greetd would spawn a session that exits
          immediately, and — because `default_session` is tuigreet — the visible
          symptom is a greeter that flickers rather than an error.
        '';
      }
    ];

    # Log straight into Hyprland once, then get out of the way.
    #
    # `command` is the bare name, not a store path: greetd runs the session
    # command through the user's login shell, so `Hyprland` resolves the same
    # way tuigreet's wayland-session entry does (Exec=Hyprland), which means a
    # Home-Manager-provided wrapper wins over the system one exactly as it does
    # on a manual login. A pinned ${config.programs.hyprland.package} path would
    # quietly diverge from what logging in by hand gives you.
    #
    # `default_session` is deliberately left alone (tuigreet). initial_session
    # runs on greetd's *first* start only; everything after — logout, compositor
    # crash, `systemctl restart greetd` — falls through to the greeter.
    #
    # Not setting `services.greetd.restart`: the nixpkgs module already defaults
    # it to `!(settings ? initial_session)`, i.e. off as soon as this attribute
    # exists, because a restarting greetd would re-trigger autologin forever.
    # The accepted cost is that a greetd process crash is not self-healing —
    # recover with `systemctl restart greetd` from a VT/SSH, or reboot. greetd
    # does not crash in practice, and an autologin loop is strictly worse.
    services.greetd.settings.initial_session = {
      command = "Hyprland";
      user = config.custom.user.name;
    };
  };
}
