//! Daemon configuration.
//!
//! Generated by the NixOS module as `/etc/oligarchy/p2p/config.json` — the same
//! `pkgs.writeText (builtins.toJSON …)` shape `modules/oligarchy-plugins` uses
//! for `policy.json`. Nothing here is discovered at runtime; if the module did
//! not declare it, it does not exist.

use anyhow::{bail, Context, Result};
use serde::Deserialize;
use std::net::IpAddr;
use std::path::Path;

#[derive(Debug, Clone, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Config {
    /// Loopback only. Enforced again at bind time — see `validate`.
    pub bind_address: String,
    pub port: u16,
    /// Advertised in `nix-cache-info`. Must match the local store or Nix
    /// refuses the cache outright.
    pub store_dir: String,
    /// Advertised in `nix-cache-info`. Lower is consulted first; cache.nixos.org
    /// is 40.
    pub priority: u32,
    /// Upstream binary caches, tried in order.
    pub upstreams: Vec<String>,
    /// Seconds to wait for an upstream to answer.
    pub upstream_timeout_secs: u64,
    pub state_dir: String,
    /// Cache ceiling, e.g. `"20G"`. Parsed by `cache::parse_size`.
    pub max_cache_size: String,
    /// Populate the artifact cache from upstream fetches.
    pub cache_downloaded: bool,
    /// Answer from the local Nix store when we already hold the path.
    pub serve_from_store: bool,

    /// `"none"` or `"lan"`. No sniffing and no fallback between transports:
    /// the one place a config becomes an execution strategy.
    pub transport: String,
    /// Peers as `ip:port`, private ranges only.
    pub peers: Vec<String>,
    /// Seconds a peer has to answer before we give up and go upstream.
    pub peer_timeout_secs: u64,
    /// Serve the peer surface on this address, or `null` to serve nobody.
    pub peer_listen: Option<String>,
    pub peer_port: u16,

    /// BitTorrent swarm port, advertised to peers in `/peer/v1/info`.
    pub swarm_port: u16,
    /// Below this many bytes an artifact never enters a swarm. This closure's
    /// median NAR is 355 KiB; 4 MiB covers 96% of the bytes with 16% of the
    /// swarms. See docs/p2p-substituter-roadmap.md §4.1.
    pub min_artifact_size: String,
    /// Bytes per second, or 0 for unlimited.
    pub swarm_upload_bps: u32,
    pub swarm_download_bps: u32,

    /// Whether this host publishes packages its operator declared in
    /// `servePackages`.
    ///
    /// A bool and **nothing more**, deliberately. The path list and the signing
    /// key reach `oligarchy-p2pd seed` as arguments on its own unit's
    /// `ExecStart`; neither appears here, because this file is what the
    /// *daemon* reads and the daemon must not so much as know where the key
    /// lives. What it needs to know is only: that an empty `upstreams` is
    /// intentional rather than a misconfiguration, and that a narinfo resolved
    /// out of `declared/` has no upstream to fall through to.
    pub serve_declared: bool,
}

impl Config {
    pub fn load(path: &Path) -> Result<Self> {
        let text = std::fs::read_to_string(path)
            .with_context(|| format!("reading config {}", path.display()))?;
        let cfg: Config = serde_json::from_str(&text)
            .with_context(|| format!("parsing config {}", path.display()))?;
        cfg.validate()?;
        Ok(cfg)
    }

    fn validate(&self) -> Result<()> {
        let ip: IpAddr = self
            .bind_address
            .parse()
            .with_context(|| format!("bind_address {:?} is not an IP", self.bind_address))?;
        // The module asserts this too. Both, because the two can drift and the
        // consequence of drift is a Nix cache exposed to the LAN that will
        // happily proxy any store path it can reach.
        if !ip.is_loopback() {
            bail!(
                "bind_address {ip} is not a loopback address. The adapter serves \
                 the Nix binary cache protocol with no authentication; it is \
                 reachable by the local nix-daemon and nothing else by design."
            );
        }
        // A pure seeder is a legitimate configuration: a build host that
        // publishes only what it built and proxies nothing. Anything else with
        // no upstream can serve nothing, and every narinfo lookup would be a
        // 404 Nix caches for an hour.
        if self.upstreams.is_empty() && !self.serve_declared {
            bail!(
                "no upstreams configured and nothing declared in servePackages — \
                 the adapter would have nothing to serve, and every narinfo \
                 lookup would be a 404 Nix caches for an hour"
            );
        }
        for u in &self.upstreams {
            // `?trusted=1` on a store URI makes Nix accept unsigned paths from
            // it (StoreConfig::isTrusted, store-api.hh). Reproduced on real
            // hardware in Stage 0 spike 11: silent, exit 0, no warning. It has
            // no meaning for an HTTP client like ours, so its presence here can
            // only be a copy-paste from a substituter list — refuse it loudly
            // rather than let it look load-bearing.
            if u.contains("trusted=") {
                bail!(
                    "upstream {u:?} carries a `trusted=` parameter. That flag \
                     disables signature checking where Nix honours it; it must \
                     never appear anywhere in this subsystem."
                );
            }
            if !(u.starts_with("http://") || u.starts_with("https://")) {
                bail!("upstream {u:?} must be http:// or https://");
            }
        }
        if self.store_dir.is_empty() {
            bail!("store_dir must be set");
        }
        crate::cache::parse_size(&self.max_cache_size)?;
        if !matches!(self.transport.as_str(), "none" | "lan" | "bittorrent") {
            bail!(
                "unknown transport {:?}; expected \"none\", \"lan\" or \"bittorrent\"",
                self.transport
            );
        }
        crate::cache::parse_size(&self.min_artifact_size)?;
        if let Some(a) = &self.peer_listen {
            let ip: IpAddr = a
                .parse()
                .with_context(|| format!("peer_listen {a:?} is not an IP"))?;
            // The peer surface is the one listener that is allowed off
            // loopback, so it is the one that has to justify itself. A wildcard
            // is permitted — reachability is governed by the firewall, per the
            // repo's per-interface `openFirewall` convention — but a public
            // unicast address is not: this protocol has no authentication and
            // serves artifacts, and the LAN transport does not leave the local
            // network.
            if !(ip.is_unspecified() || crate::transport::lan::is_lan_address(&ip)) {
                bail!(
                    "peer_listen {ip} is a routable address. The peer surface is \
                     unauthenticated and LAN-scoped; bind a private address or \
                     0.0.0.0 and control reach with the firewall."
                );
            }
        }
        Ok(())
    }

    /// Upstream base with any trailing slash removed, so joining is unambiguous.
    pub fn upstream_bases(&self) -> Vec<&str> {
        self.upstreams.iter().map(|u| u.trim_end_matches('/')).collect()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn base() -> serde_json::Value {
        serde_json::json!({
            "bind_address": "127.0.0.1",
            "port": 5111,
            "store_dir": "/nix/store",
            "priority": 30,
            "upstreams": ["https://cache.nixos.org"],
            "upstream_timeout_secs": 20,
            "state_dir": "/var/lib/oligarchy/p2p",
            "max_cache_size": "20G",
            "cache_downloaded": true,
            "serve_from_store": true,
            "transport": "none",
            "peers": [],
            "peer_timeout_secs": 10,
            "peer_listen": null,
            "peer_port": 5112,
            "swarm_port": 6881,
            "min_artifact_size": "4M",
            "swarm_upload_bps": 0,
            "swarm_download_bps": 0,
            "serve_declared": false
        })
    }

    fn load(v: serde_json::Value) -> Result<Config> {
        let c: Config = serde_json::from_value(v)?;
        c.validate()?;
        Ok(c)
    }

    #[test]
    fn the_default_shape_loads() {
        assert_eq!(load(base()).unwrap().port, 5111);
    }

    #[test]
    fn refuses_a_non_loopback_bind() {
        let mut v = base();
        v["bind_address"] = "0.0.0.0".into();
        let e = load(v).unwrap_err().to_string();
        assert!(e.contains("loopback"), "{e}");
    }

    #[test]
    fn refuses_an_upstream_carrying_trusted() {
        // Stage 0 spike 11 is why this is a refusal and not a warning.
        let mut v = base();
        v["upstreams"] = serde_json::json!(["https://cache.nixos.org?trusted=1"]);
        let e = load(v).unwrap_err().to_string();
        assert!(e.contains("trusted="), "{e}");
    }

    #[test]
    fn refuses_unknown_config_keys() {
        // deny_unknown_fields: a setting the module thinks it is passing but
        // this binary does not understand must be an error, not a silent
        // default. Same rule as plugind's Request::Install.
        let mut v = base();
        v["seedDownloaded"] = true.into();
        assert!(load(v).is_err());
    }

    #[test]
    fn refuses_a_cache_size_it_cannot_parse() {
        let mut v = base();
        v["max_cache_size"] = "twenty gigs".into();
        assert!(load(v).is_err());
    }

    #[test]
    fn refuses_an_unknown_transport() {
        // No sniffing, no silent fallback to "none": a typo in the module must
        // be a startup failure, not a machine that quietly has no peers.
        let mut v = base();
        v["transport"] = "carrier-pigeon".into();
        assert!(load(v).is_err());
    }

    #[test]
    fn accepts_the_bittorrent_transport() {
        let mut v = base();
        v["transport"] = "bittorrent".into();
        assert!(load(v).is_ok());
    }

    #[test]
    fn refuses_a_min_artifact_size_it_cannot_parse() {
        let mut v = base();
        v["min_artifact_size"] = "four megs".into();
        assert!(load(v).is_err());
    }

    #[test]
    fn refuses_a_routable_peer_listen_address() {
        let mut v = base();
        v["peer_listen"] = "203.0.113.7".into();
        let e = load(v).unwrap_err().to_string();
        assert!(e.contains("routable"), "{e}");
    }

    #[test]
    fn allows_a_wildcard_or_private_peer_listen() {
        for a in ["0.0.0.0", "192.168.1.10", "::"] {
            let mut v = base();
            v["peer_listen"] = a.into();
            assert!(load(v).is_ok(), "rejected {a}");
        }
    }

    #[test]
    fn a_pure_seeder_needs_no_upstream() {
        // A build host that publishes only what it built and proxies nothing
        // is a legitimate configuration, and the `seed` unit that populates it
        // loads this same config — so refusing it here would make the unit
        // that exists for this case unable to start on exactly this case.
        let mut c = base();
        c["upstreams"] = serde_json::json!([]);
        c["serve_declared"] = serde_json::json!(true);
        load(c).expect("a pure seeder was refused");
    }

    #[test]
    fn refuses_an_empty_upstream_list() {
        let mut v = base();
        v["upstreams"] = serde_json::json!([]);
        assert!(load(v).is_err());
    }
}
