//! Daemon configuration.
//!
//! Generated by the NixOS module as `/etc/oligarchy/p2p/config.json` — the same
//! `pkgs.writeText (builtins.toJSON …)` shape `modules/oligarchy-plugins` uses
//! for `policy.json`. Nothing here is discovered at runtime; if the module did
//! not declare it, it does not exist.

use anyhow::{bail, Context, Result};
use serde::Deserialize;
use std::net::IpAddr;
use std::path::Path;

#[derive(Debug, Clone, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Config {
    /// Loopback only. Enforced again at bind time — see `validate`.
    pub bind_address: String,
    pub port: u16,
    /// Advertised in `nix-cache-info`. Must match the local store or Nix
    /// refuses the cache outright.
    pub store_dir: String,
    /// Advertised in `nix-cache-info`. Lower is consulted first; cache.nixos.org
    /// is 40.
    pub priority: u32,
    /// Upstream binary caches, tried in order.
    pub upstreams: Vec<String>,
    /// Seconds to wait for an upstream to answer.
    pub upstream_timeout_secs: u64,
    pub state_dir: String,
    /// Cache ceiling, e.g. `"20G"`. Parsed by `cache::parse_size`.
    pub max_cache_size: String,
    /// Populate the artifact cache from upstream fetches.
    pub cache_downloaded: bool,
    /// Answer from the local Nix store when we already hold the path.
    pub serve_from_store: bool,
}

impl Config {
    pub fn load(path: &Path) -> Result<Self> {
        let text = std::fs::read_to_string(path)
            .with_context(|| format!("reading config {}", path.display()))?;
        let cfg: Config = serde_json::from_str(&text)
            .with_context(|| format!("parsing config {}", path.display()))?;
        cfg.validate()?;
        Ok(cfg)
    }

    fn validate(&self) -> Result<()> {
        let ip: IpAddr = self
            .bind_address
            .parse()
            .with_context(|| format!("bind_address {:?} is not an IP", self.bind_address))?;
        // The module asserts this too. Both, because the two can drift and the
        // consequence of drift is a Nix cache exposed to the LAN that will
        // happily proxy any store path it can reach.
        if !ip.is_loopback() {
            bail!(
                "bind_address {ip} is not a loopback address. The adapter serves \
                 the Nix binary cache protocol with no authentication; it is \
                 reachable by the local nix-daemon and nothing else by design."
            );
        }
        if self.upstreams.is_empty() {
            bail!("no upstreams configured — the stage-1 adapter has nothing to proxy");
        }
        for u in &self.upstreams {
            // `?trusted=1` on a store URI makes Nix accept unsigned paths from
            // it (StoreConfig::isTrusted, store-api.hh). Reproduced on real
            // hardware in Stage 0 spike 11: silent, exit 0, no warning. It has
            // no meaning for an HTTP client like ours, so its presence here can
            // only be a copy-paste from a substituter list — refuse it loudly
            // rather than let it look load-bearing.
            if u.contains("trusted=") {
                bail!(
                    "upstream {u:?} carries a `trusted=` parameter. That flag \
                     disables signature checking where Nix honours it; it must \
                     never appear anywhere in this subsystem."
                );
            }
            if !(u.starts_with("http://") || u.starts_with("https://")) {
                bail!("upstream {u:?} must be http:// or https://");
            }
        }
        if self.store_dir.is_empty() {
            bail!("store_dir must be set");
        }
        crate::cache::parse_size(&self.max_cache_size)?;
        Ok(())
    }

    /// Upstream base with any trailing slash removed, so joining is unambiguous.
    pub fn upstream_bases(&self) -> Vec<&str> {
        self.upstreams.iter().map(|u| u.trim_end_matches('/')).collect()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn base() -> serde_json::Value {
        serde_json::json!({
            "bind_address": "127.0.0.1",
            "port": 5111,
            "store_dir": "/nix/store",
            "priority": 30,
            "upstreams": ["https://cache.nixos.org"],
            "upstream_timeout_secs": 20,
            "state_dir": "/var/lib/oligarchy/p2p",
            "max_cache_size": "20G",
            "cache_downloaded": true,
            "serve_from_store": true
        })
    }

    fn load(v: serde_json::Value) -> Result<Config> {
        let c: Config = serde_json::from_value(v)?;
        c.validate()?;
        Ok(c)
    }

    #[test]
    fn the_default_shape_loads() {
        assert_eq!(load(base()).unwrap().port, 5111);
    }

    #[test]
    fn refuses_a_non_loopback_bind() {
        let mut v = base();
        v["bind_address"] = "0.0.0.0".into();
        let e = load(v).unwrap_err().to_string();
        assert!(e.contains("loopback"), "{e}");
    }

    #[test]
    fn refuses_an_upstream_carrying_trusted() {
        // Stage 0 spike 11 is why this is a refusal and not a warning.
        let mut v = base();
        v["upstreams"] = serde_json::json!(["https://cache.nixos.org?trusted=1"]);
        let e = load(v).unwrap_err().to_string();
        assert!(e.contains("trusted="), "{e}");
    }

    #[test]
    fn refuses_unknown_config_keys() {
        // deny_unknown_fields: a setting the module thinks it is passing but
        // this binary does not understand must be an error, not a silent
        // default. Same rule as plugind's Request::Install.
        let mut v = base();
        v["seedDownloaded"] = true.into();
        assert!(load(v).is_err());
    }

    #[test]
    fn refuses_a_cache_size_it_cannot_parse() {
        let mut v = base();
        v["max_cache_size"] = "twenty gigs".into();
        assert!(load(v).is_err());
    }

    #[test]
    fn refuses_an_empty_upstream_list() {
        let mut v = base();
        v["upstreams"] = serde_json::json!([]);
        assert!(load(v).is_err());
    }
}
