// Compiles the tar-header judge: arca/arca.gen.c (generated by Exsecutor's
// exsc, see arca/PROVENANCE.md) and arca/shim.c (its one import).
fn main() {
    println!("cargo:rerun-if-changed=arca/arca.gen.c");
    println!("cargo:rerun-if-changed=arca/shim.c");
    cc::Build::new()
        .file("arca/arca.gen.c")
        .file("arca/shim.c")
        .std("c11")
        // The emitted prologue refuses -ffast-math with an #error.
        .flag_if_supported("-fno-fast-math")
        // Every unit carries the whole helper set; unused ones are expected.
        .flag_if_supported("-Wno-unused-function")
        .compile("arca");
}
