# `nix run .#minecraft-server-dev` — run the real Paper + Geyser + Floodgate
# stack in a scratch directory, as your own user, without touching the system.
#
# WHY THIS EXISTS. The VM gate (`nix build .#test-minecraft-server`) stubs Paper,
# because a test VM is offline and Paper ships Paperclip, which downloads
# Mojang's server jar on first start. So the gate proves the module's wiring —
# unit, sandbox, firewall scoping, jar materialisation — and proves nothing at
# all about whether a Bedrock client can actually connect. This runner is the
# other half: real jars, real JVM, real ports, and you point a real client at it.
#
# It shares ./config.nix with the NixOS module verbatim, so what you are testing
# here is the configuration the service will run. That is the entire point; a
# runner with its own slightly-different config would be worse than nothing.
#
# What it deliberately does NOT share with the service:
#   - no systemd, no `minecraft` user, no sandbox   (runs as you)
#   - no tunnel, and the ports bind wherever you say (default loopback)
# So this tests the SERVER, not the reachability boundary. The boundary is the
# module's job and the VM gate's assertion.
{ lib
, writeShellApplication
, formats
, jq
, coreutils
, callPackage
}:

let
  paper = callPackage ./pkgs/papermc.nix { };
  geyser = callPackage ./pkgs/geyser-spigot.nix { };
  floodgate = callPackage ./pkgs/floodgate-spigot.nix { };

  javaPort = 25565;
  bedrockPort = 19132;

  yaml = formats.yaml { };

  cfg = import ./config.nix {
    inherit javaPort bedrockPort;
    # Loopback by default: this is a scratch server on your workstation, not
    # something that should appear on the LAN because you were testing.
    bindAddress = "127.0.0.1";
    mtu = 1200;
    geyserConfigVersion = geyser.configVersion;
    floodgateConfigVersion = floodgate.configVersion;
  };

  geyserConfig = yaml.generate "geyser-config.yml" cfg.geyser;
  floodgateConfig = yaml.generate "floodgate-config.yml" cfg.floodgate;
  bstatsConfig = yaml.generate "bstats-config.yml" cfg.bstats;

  serverProperties = builtins.toFile "server.properties" (
    "# Generated by `nix run .#minecraft-server-dev` — regenerated every run.\n"
    + lib.concatStringsSep "\n" (
      lib.mapAttrsToList
        (k: v: "${k}=${if builtins.isBool v then lib.boolToString v else toString v}")
        (cfg.serverProperties // {
          motd = "Oligarchy dev server";
          max-players = 8;
          # A scratch world should be cheap to generate and cheap to delete.
          level-name = "devworld";
          view-distance = 8;
          spawn-protection = 0;
        })
    ) + "\n"
  );
in
writeShellApplication {
  name = "oligarchy-minecraft-dev";

  runtimeInputs = [ paper jq coreutils ];

  text = ''
    # ── Arguments ────────────────────────────────────────────────────────────
    DIR="''${OLIGARCHY_MC_DIR:-''${XDG_CACHE_HOME:-$HOME/.cache}/oligarchy-minecraft-dev}"
    ACCEPT_EULA=0
    HEAP="2G"
    RESET=0

    usage() {
      cat <<'USAGE'
    oligarchy-minecraft-dev — run Paper + Geyser + Floodgate in a scratch dir

      --accept-eula     agree to Mojang's EULA (https://aka.ms/MinecraftEULA)
      --dir PATH        state directory (default: $XDG_CACHE_HOME/oligarchy-minecraft-dev)
      --heap SIZE       JVM heap, Xmx and Xms both (default: 2G)
      --reset           delete the state directory first, including the world
      -h, --help        this

    Java clients connect to  localhost:25565
    Bedrock clients connect to  127.0.0.1  port 19132
    USAGE
    }

    while [ $# -gt 0 ]; do
      case "$1" in
        --accept-eula) ACCEPT_EULA=1; shift ;;
        --dir) DIR="$2"; shift 2 ;;
        --heap) HEAP="$2"; shift 2 ;;
        --reset) RESET=1; shift ;;
        -h|--help) usage; exit 0 ;;
        *) echo "unknown argument: $1" >&2; usage >&2; exit 2 ;;
      esac
    done

    # Agreeing to a legal document on someone's behalf is not something a script
    # gets to do quietly, so this is an explicit flag rather than a default.
    if [ "$ACCEPT_EULA" -ne 1 ]; then
      echo "Running a Minecraft server means agreeing to Mojang's EULA:" >&2
      echo "  https://aka.ms/MinecraftEULA" >&2
      echo "Re-run with --accept-eula once you have." >&2
      exit 1
    fi

    if [ "$RESET" -eq 1 ] && [ -d "$DIR" ]; then
      echo "==> removing $DIR"
      rm -rf -- "$DIR"
    fi

    mkdir -p "$DIR/plugins"
    cd "$DIR"

    printf 'eula=true\n' > eula.txt

    # ── Jars and configuration ───────────────────────────────────────────────
    # Symlinks under fixed, version-less names, exactly as the NixOS module does
    # it: a build number in the filename would leave the old jar beside the new
    # one on a re-pin and Paper would load the plugin twice.
    ln -sfn ${geyser}/share/geyser/Geyser-Spigot.jar plugins/Geyser-Spigot.jar
    ln -sfn ${floodgate}/share/floodgate/floodgate-spigot.jar plugins/floodgate-spigot.jar

    # Copies, never symlinks: Geyser's ConfigLoader calls loader.save() and
    # treats the resulting EROFS IOException as fatal.
    install -Dm644 ${geyserConfig}    plugins/Geyser-Spigot/config.yml
    install -Dm644 ${floodgateConfig} plugins/floodgate/config.yml
    install -Dm644 ${bstatsConfig}    plugins/bStats/config.yml
    install -Dm644 ${serverProperties} server.properties

    # NOT touched: plugins/floodgate/key.pem. Floodgate generates that keypair
    # on first start and Geyser, in the same JVM, picks it up on its own.

    cat <<EOF
    ==> Oligarchy Minecraft dev server
        state      $DIR
        paper      ${paper.version}   (Minecraft ${paper.mcVersion}, protocol ${toString paper.javaProtocolVersion})
        geyser     ${geyser.version}  (speaks Java ${geyser.javaMinecraftVersion}, protocol ${toString geyser.javaProtocolVersion})
        floodgate  ${floodgate.version}
        Bedrock clients supported: ${geyser.bedrockVersions}

        Java     -> localhost:${toString javaPort}
        Bedrock  -> 127.0.0.1 port ${toString bedrockPort}

        First start downloads Mojang's server jar (Paper ships Paperclip) and
        generates a world, so it takes a minute. Type 'stop' to shut down.
    EOF

    # Paper's wrapper is `jre "$@" -jar papermc.jar nogui`, so arguments here
    # land as JVM options — the same shape as the unit's ExecStart.
    exec minecraft-server "-Xmx$HEAP" "-Xms$HEAP"
  '';

  meta = {
    description = "Run the Oligarchy Minecraft server stack in a scratch directory";
    mainProgram = "oligarchy-minecraft-dev";
  };
}
