#define EXS_NEED_FLOAT 0
/* exsecutor: reach backend */
/* Generated by exsc --emitte c. Do not edit: the text of this prologue is a
 * function of exsc's own bytes (docs/design/c-backend.md D5), the way the
 * reference backend's prelude blob is. */
#include <stdint.h>
#include <limits.h>
#ifndef EXS_NEED_FLOAT
#define EXS_NEED_FLOAT 1
#endif
#if EXS_NEED_FLOAT
#include <float.h>
#endif

#if !defined(__GNUC__) && !defined(__clang__)
# error "exsecutor: the emitted C is C11 plus a GCC/Clang extension set (ADR 0012)"
#endif
#if !defined(__BYTE_ORDER__) || !defined(__ORDER_LITTLE_ENDIAN__) || !defined(__ORDER_BIG_ENDIAN__)
# error "exsecutor: __BYTE_ORDER__ is required to select the nativus helpers"
#endif
#if defined(__FAST_MATH__)
# error "exsecutor: -ffast-math is refused (spec 5.4)"
#endif
#if defined(__FINITE_MATH_ONLY__) && __FINITE_MATH_ONLY__
# error "exsecutor: -ffinite-math-only is refused (spec 5.4)"
#endif

#if EXS_NEED_FLOAT
/* ---- IEEE binary32/64: the numeric subset's one target (spec 5.4) -------
 * ADR 0012's rung (b), spelled with <float.h> exactly as ADR 0012 names it
 * -- freestanding-safe, unlike __STDC_IEC_559__ (which a freestanding
 * implementation may define without honouring). `float` is binary32 and
 * `double` binary64, and no operation gains precision: FLT_EVAL_METHOD 0
 * is what makes `float op float` a FLOAT operation in C rather than a
 * double one (C's usual arithmetic conversions leave the type alone, but
 * only an evaluation method of 0 leaves the RESULT alone). Subnormals are
 * values (subnormales conservata); where C11's <float.h> stays silent
 * about them (the *_HAS_SUBNORM macros are optional before C23) the
 * runtime's MXCSR/FPCR image is what enforces it -- FTZ and DAZ clear,
 * which the reference prelude's 0x1F80 image also carries. */
_Static_assert(FLT_RADIX == 2, "exsecutor: the numeric subset is IEEE binary32/64 (spec 5.4)");
_Static_assert(FLT_MANT_DIG == 24 && DBL_MANT_DIG == 53,
               "exsecutor: float is binary32 and double is binary64");
_Static_assert(FLT_MAX_EXP == 128 && DBL_MAX_EXP == 1024,
               "exsecutor: binary32/64 exponent widths");
#if FLT_EVAL_METHOD != 0
# error "exsecutor: FLT_EVAL_METHOD must be 0 (spec 5.4: one rounding, in the operands' own width)"
#endif
#if defined(FLT_HAS_SUBNORM) && FLT_HAS_SUBNORM != 1
# error "exsecutor: float subnormals must be preserved (spec 5.4 subnormales conservata)"
#endif
#if defined(DBL_HAS_SUBNORM) && DBL_HAS_SUBNORM != 1
# error "exsecutor: double subnormals must be preserved (spec 5.4 subnormales conservata)"
#endif

/* Contraction (spec 5.4 contractio explicita; ADR 0012 problem 1). One IR
 * op is one C statement, so no emitted statement ever holds a
 * multiply-and-add tree to contract -- `fma` is the only contraction the
 * language has, it is refused by name in both backends, and this pragma is
 * the belt to that brace. `#pragma STDC FP_CONTRACT OFF` is NOT emitted:
 * measured to do nothing in both compilers, and GCC warns about it under
 * -Wall (c-backend.md D3, finding 12). Clang has nothing that works from
 * inside the source (`#pragma clang fp contract(off)` does not override a
 * command-line -ffp-contract=fast), so nothing is said to it and nothing
 * is lied about. */
#if defined(__GNUC__) && !defined(__clang__)
# pragma GCC optimize("fp-contract=off")
#endif
#endif /* EXS_NEED_FLOAT */

_Static_assert(CHAR_BIT == 8, "exsecutor: CHAR_BIT must be 8");
_Static_assert((-1 & 3) == 3, "exsecutor: two's complement");
_Static_assert(sizeof(unsigned) * CHAR_BIT >= 32, "exsecutor: unsigned holds a byte and a shift");

/* The trap hook: the ONE symbol a library-mode unit imports. Whoever links
 * it supplies the body (c-backend.md D1). Kinds are prelude/README.md's:
 * 1 numeric (overflow, a shift count past the width, a failed chk),
 * 5 terminus. */
_Noreturn void exsrt_abortus(unsigned kind);

/* Every integer value of any uN or iN is held in a uint64_t in canonical
 * form (ssa-ir.md 2.2): a uN zero-extended, an iN sign-extended. Every
 * helper assumes canonical inputs and returns a canonical result. All
 * arithmetic is on uint64_t, whose overflow C defines as modular, so no
 * emitted operation is undefined and -fwrapv / -ftrapv are irrelevant. */
static inline uint64_t exsi_mask(unsigned n)
{ return n == 64 ? UINT64_MAX : (UINT64_C(1) << n) - 1; }
static inline uint64_t exsi_norm_u(uint64_t x, unsigned n)
{ return x & exsi_mask(n); }
static inline uint64_t exsi_norm_i(uint64_t x, unsigned n)
{ uint64_t s = UINT64_C(1) << (n - 1); return ((x & exsi_mask(n)) ^ s) - s; }

#if EXS_NEED_FLOAT
/* Floats from their bits -- `fconst`'s round-trip. `fconst F bits` carries
 * the RAW bit pattern (ssa-ir.md 2.3: bits, never decimal text) and it must
 * come back exactly: payload bits included (a NaN's payload survives fneg),
 * sign included (-0.0 is a different constant from 0.0), subnormal bits
 * included (subnormales conservata). A C floating literal cannot spell any
 * of that -- a hex floating literal for an out-of-range pattern loses the
 * NaN payload and the quiet bit -- so the pattern is written as an integer
 * constant and re-read through the object representation:
 * __builtin_memcpy, the GCC-recommended bit-cast, already measured and on
 * D3's extension list for `copy n` (c-backend.md finding 13). Assumes a
 * float's byte order is the integer byte order -- true of every target in
 * scope: x86_64, riscv64 and mips64 are each uniform in their byte order,
 * which is what the emitted `exsi_ld_n` selection also assumes. */
static inline float exsi_f32_from_bits(uint32_t b)
{ float f; __builtin_memcpy(&f, &b, sizeof f); return f; }
static inline double exsi_f64_from_bits(uint64_t b)
{ double d; __builtin_memcpy(&d, &b, sizeof d); return d; }

/* The way back, for `store F`: the float's bit pattern as the integer the
 * byte-store helpers carry. Same bit-cast, same assumption a few lines
 * above (a float's byte order is the integer byte order) -- the round trip
 * store-then-load is the identity on every --hospes row, which is all
 * memory consistency asks of a bit pattern with no numeric reading. */
static inline uint32_t exsi_bits_from_f32(float f)
{ uint32_t b; __builtin_memcpy(&b, &f, sizeof b); return b; }
static inline uint64_t exsi_bits_from_f64(double d)
{ uint64_t b; __builtin_memcpy(&b, &d, sizeof b); return b; }

/* The vector float group (spec 5.4's vf32.N/vf64.N; ssa-ir.md 2.2: N lanes
 * of binary32/binary64, N in {2,4,8}), as C's vector_size extension -- one
 * of the GCC/Clang extensions ADR 0012's set already carries. One IR
 * vadd/vsub/vmul/vdiv is one C statement on the whole vector (the one
 * op-per-statement rule), and the operator's elementwise lowering is the
 * ONE IEEE rounding per lane the reference's packed addps/addpd carries:
 * GCC and Clang both lower vector_size arithmetic elementwise on x86-64
 * and soft-lower it on the mips64-none cross target, which is what keeps
 * cross=yes alive for this wave. NO intrinsics and no <emmintrin.h>-family
 * header: those spellings do not exist on the cross target. */
typedef float exs_vf32_2 __attribute__((vector_size(8)));
typedef float exs_vf32_4 __attribute__((vector_size(16)));
typedef float exs_vf32_8 __attribute__((vector_size(32)));
typedef double exs_vf64_2 __attribute__((vector_size(16)));
typedef double exs_vf64_4 __attribute__((vector_size(32)));
typedef double exs_vf64_8 __attribute__((vector_size(64)));
/* The N = 8 helpers carry 32/64-byte vectors, and both compilers note at
 * their definitions (GCC) or call sites (Clang) that passing such a vector
 * without AVX enabled "changes the ABI" (-Wpsabi). That warning is a
 * statement about TWO translation units compiled with different -m flags
 * sharing a function boundary -- and no boundary here carries a vector:
 * the helpers are `static inline` inside the single emitted unit, and the
 * unit's one imported/exported symbol (exs_initium's unsigned char *) is a
 * scalar. The note is noise for this blob and is switched off for it, the
 * way -Wno-unused-function is for the rest of it (recorded, not hidden). */
#if defined(__clang__)
# pragma clang diagnostic ignored "-Wpsabi"
#elif defined(__GNUC__)
# pragma GCC diagnostic ignored "-Wpsabi"
#endif
_Static_assert(sizeof(exs_vf32_2) == 8 && sizeof(exs_vf32_4) == 16 &&
               sizeof(exs_vf32_8) == 32,
               "exsecutor: a vf32.N is N binary32 lanes, packed (spec 5.4)");
_Static_assert(sizeof(exs_vf64_2) == 16 && sizeof(exs_vf64_4) == 32 &&
               sizeof(exs_vf64_8) == 64,
               "exsecutor: a vf64.N is N binary64 lanes, packed (spec 5.4)");

/* A vector in memory is its lanes' raw IEEE images, back to back in
 * subscript order, each element in the target's byte order -- the same
 * assumption the scalar helpers above name, so the nativus round trip is
 * the identity on every --hospes row. The load/store helpers are memcpy
 * bit baggage exactly the way the scalar float path's from_bits/bits_from
 * helpers are: no lane is read numerically on the path, so a NaN payload,
 * -0.0's sign and a subnormal's bits survive every copy (subnormales
 * conservata). */
static inline exs_vf32_2 exsi_ld_vf32_2(const unsigned char *p)
{ exs_vf32_2 v; __builtin_memcpy(&v, p, sizeof v); return v; }
static inline exs_vf32_4 exsi_ld_vf32_4(const unsigned char *p)
{ exs_vf32_4 v; __builtin_memcpy(&v, p, sizeof v); return v; }
static inline exs_vf32_8 exsi_ld_vf32_8(const unsigned char *p)
{ exs_vf32_8 v; __builtin_memcpy(&v, p, sizeof v); return v; }
static inline exs_vf64_2 exsi_ld_vf64_2(const unsigned char *p)
{ exs_vf64_2 v; __builtin_memcpy(&v, p, sizeof v); return v; }
static inline exs_vf64_4 exsi_ld_vf64_4(const unsigned char *p)
{ exs_vf64_4 v; __builtin_memcpy(&v, p, sizeof v); return v; }
static inline exs_vf64_8 exsi_ld_vf64_8(const unsigned char *p)
{ exs_vf64_8 v; __builtin_memcpy(&v, p, sizeof v); return v; }
static inline void exsi_st_vf32_2(unsigned char *p, exs_vf32_2 v)
{ __builtin_memcpy(p, &v, sizeof v); }
static inline void exsi_st_vf32_4(unsigned char *p, exs_vf32_4 v)
{ __builtin_memcpy(p, &v, sizeof v); }
static inline void exsi_st_vf32_8(unsigned char *p, exs_vf32_8 v)
{ __builtin_memcpy(p, &v, sizeof v); }
static inline void exsi_st_vf64_2(unsigned char *p, exs_vf64_2 v)
{ __builtin_memcpy(p, &v, sizeof v); }
static inline void exsi_st_vf64_4(unsigned char *p, exs_vf64_4 v)
{ __builtin_memcpy(p, &v, sizeof v); }
static inline void exsi_st_vf64_8(unsigned char *p, exs_vf64_8 v)
{ __builtin_memcpy(p, &v, sizeof v); }

/* itof from a signed integer's canonical bits. The carrier holds an iN
 * sign-extended (ssa-ir.md 2.2), so the two's-complement value IS the bit
 * pattern -- but C leaves a uint64_t -> int64_t conversion that does not
 * fit IMPLEMENTATION-DEFINED, a fact this prologue asserts nowhere and
 * refuses to rely on, so the bits are re-read as int64_t exactly the way
 * fconst re-reads a pattern as a float. The signed type appears here and
 * nowhere else: this is a conversion into a float, not arithmetic, and the
 * one-op-per-statement rule keeps it out of any expression a compiler
 * could contract. */
static inline int64_t exsi_i64_from_bits(uint64_t b)
{ int64_t s; __builtin_memcpy(&s, &b, sizeof s); return s; }

#endif /* EXS_NEED_FLOAT */

static inline uint64_t exsi_add_u(uint64_t a, uint64_t b, unsigned n)
{ uint64_t t = a + b;
  if (n == 64 ? t < a : t > exsi_mask(n)) exsrt_abortus(1);
  return t; }
static inline uint64_t exsi_add_i(uint64_t a, uint64_t b, unsigned n)
{ uint64_t t = a + b;
  if (n == 64 ? ((((a ^ t) & (b ^ t)) >> 63) != 0) : exsi_norm_i(t, n) != t)
    exsrt_abortus(1);
  return t; }
static inline uint64_t exsi_sub_u(uint64_t a, uint64_t b, unsigned n)
{ uint64_t t = a - b;
  if (n == 64 ? a < b : t > exsi_mask(n)) exsrt_abortus(1);
  return t; }
static inline uint64_t exsi_sub_i(uint64_t a, uint64_t b, unsigned n)
{ uint64_t t = a - b;
  if (n == 64 ? ((((a ^ b) & (a ^ t)) >> 63) != 0) : exsi_norm_i(t, n) != t)
    exsrt_abortus(1);
  return t; }
/* mul checks by DIVISION at every width rather than in a wider type: GCC
 * provides __int128 only where __SIZEOF_INT128__ is defined, which excludes
 * 32-bit-pointer targets such as o64 (c-backend.md finding 5). b > M / a is
 * exact. */
static inline uint64_t exsi_mul_u(uint64_t a, uint64_t b, unsigned n)
{ if (n <= 32) { uint64_t t = a * b; if (t > exsi_mask(n)) exsrt_abortus(1); return t; }
  if (a != 0 && b > exsi_mask(n) / a) exsrt_abortus(1);
  return a * b; }
static inline uint64_t exsi_mul_i(uint64_t a, uint64_t b, unsigned n)
{ uint64_t sa = a >> 63, sb = b >> 63;
  uint64_t ma = sa ? 0 - a : a, mb = sb ? 0 - b : b;   /* magnitudes; 2^63 stays 2^63 */
  uint64_t neg = sa ^ sb;
  uint64_t lim = neg ? UINT64_C(1) << (n - 1) : (UINT64_C(1) << (n - 1)) - 1;
  if (ma != 0 && mb > lim / ma) exsrt_abortus(1);
  { uint64_t p = ma * mb; return neg ? 0 - p : p; } }   /* canonical by construction */

/* div and rem -- spec 5.4 as decided 2026-09-25: the quotient TRUNCATED
 * TOWARD ZERO and the remainder's sign FOLLOWING THE DIVIDEND, so that
 * `a == (a/b)*b + (a rem b)` holds at every pair of signs. Both trap on a
 * zero divisor, and both trap on T_MIN / -1 -- `rem` included, whose
 * mathematical value there is 0: it is the remainder OF a division that
 * does not exist, and a `rem` answering 0 where its own `div` traps would
 * falsify the identity at the one pair of operands two instructions can
 * check it on. emit.inc's __bfa_emit_divrem argues the same two paragraphs
 * for the reference; these helpers are the same function, not a second
 * opinion about it.
 *
 * THE CHECKS PRECEDE THE DIVISION, where every other trapping helper above
 * checks after, and they have to for two independent reasons. The semantic
 * one: `rem`'s result carries no trace of the overflow (T_MIN rem -1 is 0,
 * a perfectly good value of T), so there is nothing to check afterwards.
 * The harness one: every fixture is compiled `-fsanitize=undefined
 * -fno-sanitize-recover=all`, so a helper that DIVIDED first would abort
 * inside UBSan -- wrong status, wrong text, exsrt_abortus never reached --
 * on precisely the two inputs whose trap is the thing being tested.
 *
 * T_MIN IS T'S OWN, NOT INT64_MIN. In `i8`, -128 / -1 is 128, which no
 * `i8` holds, and the 64-bit division of a sign-extended -128 by -1
 * computes it without a murmur; tests/ir/trap_div_minneg1.ir is that case
 * and nothing else. So the comparison is against -2^(N-1) for the operand
 * type's own N. At N = 64 the same line also stands in for the hardware's
 * divide error, which the reference likewise turns into kind 1 rather than
 * a second signal that depends on the width.
 *
 * NO SIGNED C DIVISION ANYWHERE. The signed pair divides MAGNITUDES and
 * puts the sign back, exactly as exsi_mul_i does, so the carrier's
 * implementation-defined uint64_t -> int64_t conversion is never needed
 * (this file relies on it nowhere but exsi_i64_from_bits, and then through
 * memcpy) and UBSan's signed-overflow check is never armed. `0 - x` on a
 * uint64_t is modular C, not overflow. The magnitude of T_MIN is 2^63,
 * which `0 - a` leaves as 2^63 -- still the right unsigned magnitude.
 *
 * NO NORMALISATION, and the proof rather than the habit. With a zero
 * divisor and T_MIN / -1 excluded the result is ALREADY a value of T:
 * |a/b| <= |a| for |b| >= 1, so the only out-of-range quotient is -T_MIN,
 * which is precisely the case just excluded; and |a rem b| < |b| <=
 * 2^(N-1), in range at every sign. `0 - q` on an in-range magnitude leaves
 * the value sign-extended, which is the canonical form (ssa-ir.md 2.2).
 *
 * n IS UNUSED IN THE UNSIGNED PAIR and the parameter still stays. A uN
 * quotient is at most the dividend and a uN remainder is less than the
 * divisor, so neither can leave the type, and unsigned division has no
 * T_MIN case to exclude -- but the emitter writes ONE call shape for every
 * row of the helper table, so the argument is passed and discarded the way
 * exsi_subs_u discards it. */
static inline uint64_t exsi_div_u(uint64_t a, uint64_t b, unsigned n)
{ (void)n; if (b == 0) exsrt_abortus(1); return a / b; }
static inline uint64_t exsi_rem_u(uint64_t a, uint64_t b, unsigned n)
{ (void)n; if (b == 0) exsrt_abortus(1); return a % b; }
static inline uint64_t exsi_div_i(uint64_t a, uint64_t b, unsigned n)
{ if (b == 0) exsrt_abortus(1);
  if (a == 0 - (UINT64_C(1) << (n - 1)) && b == UINT64_MAX) exsrt_abortus(1);
  { uint64_t sa = a >> 63, sb = b >> 63;
    uint64_t ma = sa ? 0 - a : a, mb = sb ? 0 - b : b;   /* magnitudes; 2^63 stays 2^63 */
    uint64_t q = ma / mb;
    return (sa ^ sb) ? 0 - q : q; } }                    /* canonical by construction */
static inline uint64_t exsi_rem_i(uint64_t a, uint64_t b, unsigned n)
{ if (b == 0) exsrt_abortus(1);
  if (a == 0 - (UINT64_C(1) << (n - 1)) && b == UINT64_MAX) exsrt_abortus(1);
  { uint64_t sa = a >> 63, sb = b >> 63;
    uint64_t ma = sa ? 0 - a : a, mb = sb ? 0 - b : b;
    uint64_t r = ma % mb;
    return sa ? 0 - r : r; } }                           /* the DIVIDEND's sign */

static inline uint64_t exsi_adds_u(uint64_t a, uint64_t b, unsigned n)
{ uint64_t t = a + b; return (n == 64 ? t < a : t > exsi_mask(n)) ? exsi_mask(n) : t; }
static inline uint64_t exsi_subs_u(uint64_t a, uint64_t b, unsigned n)
{ (void)n; return a < b ? 0 : a - b; }
static inline uint64_t exsi_adds_i(uint64_t a, uint64_t b, unsigned n)
{ uint64_t t = a + b, s = UINT64_C(1) << (n - 1);
  if (n == 64) return ((((a ^ t) & (b ^ t)) >> 63) != 0) ? ((a >> 63) ? s : s - 1) : t;
  return exsi_norm_i(t, n) != t ? ((t >> 63) ? exsi_norm_i(s, n) : s - 1) : t; }
static inline uint64_t exsi_subs_i(uint64_t a, uint64_t b, unsigned n)
{ uint64_t t = a - b, s = UINT64_C(1) << (n - 1);
  if (n == 64) return ((((a ^ b) & (a ^ t)) >> 63) != 0) ? ((a >> 63) ? s : s - 1) : t;
  return exsi_norm_i(t, n) != t ? ((t >> 63) ? exsi_norm_i(s, n) : s - 1) : t; }

/* A count >= the width traps, as spec 5.4 says it must ("traps, as + traps
 * on overflow"); after the check c < n <= 64, so every C shift below is
 * defined. A negative iN count is a huge unsigned and traps, which is what
 * the reference's `jae` does too. */
static inline uint64_t exsi_shl_u(uint64_t a, uint64_t c, unsigned n)
{ if (c >= n) exsrt_abortus(1); return exsi_norm_u(a << c, n); }
static inline uint64_t exsi_shl_i(uint64_t a, uint64_t c, unsigned n)
{ if (c >= n) exsrt_abortus(1); return exsi_norm_i(a << c, n); }
static inline uint64_t exsi_shr_u(uint64_t a, uint64_t c, unsigned n)
{ if (c >= n) exsrt_abortus(1); return a >> c; }
/* arithmetic right shift without a signed shift: the sign replicated by a
 * mask. c == 0 is split out because (x << 64) would be a shift by the
 * type's width. */
static inline uint64_t exsi_shr_i(uint64_t a, uint64_t c, unsigned n)
{ if (c >= n) exsrt_abortus(1);
  return c == 0 ? a : (a >> c) | ((0 - (a >> 63)) << (64 - c)); }

/* Byte-at-a-time, with explicit shifts: the emitted text depends on no
 * assumption about the C host's byte order and asserts none (c-backend.md
 * D2). p[i] is an unsigned char promoted to int and converted straight to
 * uint64_t by the | -- a value in 0..255, never operated on as an int. */
static inline uint64_t exsi_ld_be(const unsigned char *p, unsigned k)
{ uint64_t v = 0; unsigned i; for (i = 0; i < k; i++) v = (v << 8) | p[i]; return v; }
static inline uint64_t exsi_ld_le(const unsigned char *p, unsigned k)
{ uint64_t v = 0; unsigned i; for (i = 0; i < k; i++) v |= (uint64_t)p[i] << (8 * i); return v; }
static inline void exsi_st_be(unsigned char *p, unsigned k, uint64_t v)
{ unsigned i; for (i = 0; i < k; i++) p[i] = (unsigned char)(v >> (8 * (k - 1 - i))); }
static inline void exsi_st_le(unsigned char *p, unsigned k, uint64_t v)
{ unsigned i; for (i = 0; i < k; i++) p[i] = (unsigned char)(v >> (8 * i)); }
#if __BYTE_ORDER__ == __ORDER_LITTLE_ENDIAN__
# define exsi_ld_n exsi_ld_le
# define exsi_st_n exsi_st_le
#elif __BYTE_ORDER__ == __ORDER_BIG_ENDIAN__
# define exsi_ld_n exsi_ld_be
# define exsi_st_n exsi_st_be
#else
# error "exsecutor: unknown __BYTE_ORDER__"
#endif

_Static_assert(sizeof(void *) == 8, "exsecutor: this hospes has 64-bit addresses");

uint64_t exs_magnitudo(unsigned char *p0);
uint64_t exs_octalis(unsigned char *p0, uint64_t p1, uint64_t p2);
uint64_t exs_saltus(uint64_t p0);
uint64_t exs_nomen_iudica(unsigned char *p0, uint64_t p1);
uint64_t exs_caput_iudica(unsigned char *p0, unsigned char *p1, uint64_t p2, uint64_t p3);

uint64_t exs_magnitudo(unsigned char *p0)
{
    unsigned char *v1;
    uint64_t v2;
    uint64_t v3;
    uint64_t v4;
    unsigned char *v6;
    uint64_t v7;
    uint64_t v8;
    uint64_t v9;
    uint64_t v11;
    uint64_t v12;
    unsigned char *v14;
    uint64_t v15;
    uint64_t v16;
    uint64_t v17;
    uint64_t v19;
    uint64_t v21;
    uint64_t v22;
    unsigned char *v24;
    uint64_t v25;
    uint64_t v26;
    uint64_t v27;
    uint64_t v29;
    uint64_t v31;
    uint64_t v32;
    unsigned char *v34;
    uint64_t v35;
    uint64_t v36;
    uint64_t v37;
    uint64_t v39;
    uint64_t v41;
    uint64_t v42;
    unsigned char *v44;
    uint64_t v45;
    uint64_t v46;
    uint64_t v47;
    uint64_t v49;
    uint64_t v51;
    uint64_t v52;
    uint64_t v54;
    uint64_t v55;
    uint64_t v57;
    uint64_t v58;
    uint64_t v59;
    uint64_t v60;
    unsigned char *v62;
    uint64_t v63;
    uint64_t v64;
    uint64_t v65;
    uint64_t v67;
    uint64_t v68;
    uint64_t v71;
    uint64_t v72;
    uint64_t v74;
    uint64_t v75;
    uint64_t v77;
    unsigned char *v79;
    uint64_t v80;
    uint64_t v81;
    uint64_t v82;
    uint64_t v84;
    uint64_t v86;
    uint64_t v87;
    uint64_t v89;
    uint64_t v91;
    uint64_t v92;
    uint64_t v93;
    uint64_t v94;
    uint64_t v95;
    uint64_t v96;
    uint64_t v97;
    uint64_t v99;
    uint64_t v100;
    uint64_t v102;
    uint64_t v103;
    unsigned char *v105;
    uint64_t v106;
    uint64_t v107;
    uint64_t v108;
    uint64_t v110;
    uint64_t t54;
    uint64_t t57;
    uint64_t t74;
    uint64_t t91;
    v1 = p0;
    v2 = UINT64_C(0);
    v3 = UINT64_C(124);
    v4 = UINT64_C(512);
    if (v3 >= v4) exsrt_abortus(1);
    v6 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v3 * 1);
    v7 = exsi_norm_u(exsi_ld_n(v6 + 0, 1), 8);
    v8 = UINT64_C(128);
    v9 = (v7 == v8);
    if (v9) {
        goto b2;
    } else {
        goto b3;
    }
b2:
    v11 = UINT64_C(125);
    v12 = UINT64_C(512);
    if (v11 >= v12) exsrt_abortus(1);
    v14 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v11 * 1);
    v15 = exsi_norm_u(exsi_ld_n(v14 + 0, 1), 8);
    v16 = UINT64_C(0);
    v17 = (v15 != v16);
    if (v17) {
        goto b4;
    } else {
        goto b5;
    }
b3:
    v71 = UINT64_C(124);
    v72 = UINT64_C(135);
    t91 = v2;
    t74 = v71;
    v91 = t91;
    v74 = t74;
    goto b16;
b4:
    v19 = UINT64_C(18446744073709551615);
    return v19;
b5:
    v21 = UINT64_C(126);
    v22 = UINT64_C(512);
    if (v21 >= v22) exsrt_abortus(1);
    v24 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v21 * 1);
    v25 = exsi_norm_u(exsi_ld_n(v24 + 0, 1), 8);
    v26 = UINT64_C(0);
    v27 = (v25 != v26);
    if (v27) {
        goto b6;
    } else {
        goto b7;
    }
b6:
    v29 = UINT64_C(18446744073709551615);
    return v29;
b7:
    v31 = UINT64_C(127);
    v32 = UINT64_C(512);
    if (v31 >= v32) exsrt_abortus(1);
    v34 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v31 * 1);
    v35 = exsi_norm_u(exsi_ld_n(v34 + 0, 1), 8);
    v36 = UINT64_C(0);
    v37 = (v35 != v36);
    if (v37) {
        goto b8;
    } else {
        goto b9;
    }
b8:
    v39 = UINT64_C(18446744073709551615);
    return v39;
b9:
    v41 = UINT64_C(128);
    v42 = UINT64_C(512);
    if (v41 >= v42) exsrt_abortus(1);
    v44 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v41 * 1);
    v45 = exsi_norm_u(exsi_ld_n(v44 + 0, 1), 8);
    v46 = UINT64_C(128);
    v47 = (v45 >= v46);
    if (v47) {
        goto b10;
    } else {
        goto b11;
    }
b10:
    v49 = UINT64_C(18446744073709551615);
    return v49;
b11:
    v51 = UINT64_C(128);
    v52 = UINT64_C(136);
    t57 = v2;
    t54 = v51;
    v57 = t57;
    v54 = t54;
    goto b12;
b12:
    v55 = (v54 < v52);
    if (v55) {
        goto b13;
    } else {
        goto b14;
    }
b13:
    v58 = UINT64_C(8);
    v59 = exsi_shl_u(v57, v58, 64);
    v60 = UINT64_C(512);
    if (v54 >= v60) exsrt_abortus(1);
    v62 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v54 * 1);
    v63 = exsi_norm_u(exsi_ld_n(v62 + 0, 1), 8);
    v64 = exsi_norm_u(v63, 8);
    v65 = v59 ^ v64;
    goto b15;
b14:
    return v57;
b15:
    v67 = UINT64_C(1);
    v68 = v54 + v67;
    t57 = v65;
    t54 = v68;
    v57 = t57;
    v54 = t54;
    goto b12;
b16:
    v75 = (v74 < v72);
    if (v75) {
        goto b17;
    } else {
        goto b18;
    }
b17:
    v77 = UINT64_C(512);
    if (v74 >= v77) exsrt_abortus(1);
    v79 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v74 * 1);
    v80 = exsi_norm_u(exsi_ld_n(v79 + 0, 1), 8);
    v81 = UINT64_C(48);
    v82 = (v80 < v81);
    if (v82) {
        goto b20;
    } else {
        goto b21;
    }
b18:
    v102 = UINT64_C(135);
    v103 = UINT64_C(512);
    if (v102 >= v103) exsrt_abortus(1);
    v105 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v102 * 1);
    v106 = exsi_norm_u(exsi_ld_n(v105 + 0, 1), 8);
    v107 = UINT64_C(0);
    v108 = (v106 != v107);
    if (v108) {
        goto b24;
    } else {
        goto b25;
    }
b19:
    v99 = UINT64_C(1);
    v100 = v74 + v99;
    t91 = v97;
    t74 = v100;
    v91 = t91;
    v74 = t74;
    goto b16;
b20:
    v84 = UINT64_C(18446744073709551615);
    return v84;
b21:
    v86 = UINT64_C(55);
    v87 = (v80 > v86);
    if (v87) {
        goto b22;
    } else {
        goto b23;
    }
b22:
    v89 = UINT64_C(18446744073709551615);
    return v89;
b23:
    v92 = UINT64_C(3);
    v93 = exsi_shl_u(v91, v92, 64);
    v94 = UINT64_C(48);
    v95 = exsi_sub_u(v80, v94, 8);
    v96 = exsi_norm_u(v95, 8);
    v97 = v93 ^ v96;
    goto b19;
b24:
    v110 = UINT64_C(18446744073709551615);
    return v110;
b25:
    return v91;
}

uint64_t exs_octalis(unsigned char *p0, uint64_t p1, uint64_t p2)
{
    unsigned char *v1;
    uint64_t v2;
    uint64_t v3;
    uint64_t v4;
    uint64_t v5;
    uint64_t v6;
    uint64_t v8;
    uint64_t v9;
    uint64_t v11;
    unsigned char *v13;
    uint64_t v14;
    uint64_t v15;
    uint64_t v16;
    uint64_t v18;
    uint64_t v20;
    unsigned char *v22;
    uint64_t v23;
    uint64_t v24;
    uint64_t v25;
    uint64_t v27;
    uint64_t v30;
    uint64_t v31;
    uint64_t v33;
    uint64_t v34;
    uint64_t v35;
    uint64_t v36;
    unsigned char *v38;
    uint64_t v39;
    uint64_t v40;
    uint64_t v41;
    uint64_t v43;
    uint64_t v45;
    uint64_t t8;
    v1 = p0;
    v2 = p1;
    v3 = p2;
    v4 = exsi_add_u(v2, v3, 64);
    v5 = UINT64_C(1);
    v6 = exsi_sub_u(v4, v5, 64);
    t8 = v2;
    v8 = t8;
    goto b2;
b2:
    v9 = (v8 < v6);
    if (v9) {
        goto b3;
    } else {
        goto b4;
    }
b3:
    v11 = UINT64_C(512);
    if (v8 >= v11) exsrt_abortus(1);
    v13 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v8 * 1);
    v14 = exsi_norm_u(exsi_ld_n(v13 + 0, 1), 8);
    v15 = UINT64_C(48);
    v16 = (v14 < v15);
    if (v16) {
        goto b6;
    } else {
        goto b7;
    }
b4:
    v33 = exsi_add_u(v2, v3, 64);
    v34 = UINT64_C(1);
    v35 = exsi_sub_u(v33, v34, 64);
    v36 = UINT64_C(512);
    if (v35 >= v36) exsrt_abortus(1);
    v38 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v35 * 1);
    v39 = exsi_norm_u(exsi_ld_n(v38 + 0, 1), 8);
    v40 = UINT64_C(0);
    v41 = (v39 != v40);
    if (v41) {
        goto b10;
    } else {
        goto b11;
    }
b5:
    v30 = UINT64_C(1);
    v31 = v8 + v30;
    t8 = v31;
    v8 = t8;
    goto b2;
b6:
    v18 = UINT64_C(0);
    return v18;
b7:
    v20 = UINT64_C(512);
    if (v8 >= v20) exsrt_abortus(1);
    v22 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v8 * 1);
    v23 = exsi_norm_u(exsi_ld_n(v22 + 0, 1), 8);
    v24 = UINT64_C(55);
    v25 = (v23 > v24);
    if (v25) {
        goto b8;
    } else {
        goto b9;
    }
b8:
    v27 = UINT64_C(0);
    return v27;
b9:
    goto b5;
b10:
    v43 = UINT64_C(0);
    return v43;
b11:
    v45 = UINT64_C(1);
    return v45;
}

uint64_t exs_saltus(uint64_t p0)
{
    uint64_t v1;
    uint64_t v2;
    uint64_t v3;
    uint64_t v4;
    uint64_t v5;
    uint64_t v6;
    uint64_t v7;
    v1 = p0;
    v2 = UINT64_C(511);
    v3 = exsi_add_u(v1, v2, 64);
    v4 = UINT64_C(9);
    v5 = exsi_shr_u(v3, v4, 64);
    v6 = UINT64_C(9);
    v7 = exsi_shl_u(v5, v6, 64);
    return v7;
}

uint64_t exs_nomen_iudica(unsigned char *p0, uint64_t p1)
{
    unsigned char *v1;
    uint64_t v2;
    uint64_t v3;
    uint64_t v4;
    uint64_t v6;
    uint64_t v8;
    uint64_t v9;
    unsigned char *v11;
    uint64_t v12;
    uint64_t v13;
    uint64_t v14;
    uint64_t v16;
    uint64_t v18;
    uint64_t v19;
    uint64_t v21;
    uint64_t v22;
    uint64_t v24;
    unsigned char *v26;
    uint64_t v27;
    uint64_t v28;
    uint64_t v29;
    uint64_t v31;
    uint64_t v33;
    uint64_t v34;
    uint64_t v36;
    uint64_t v38;
    uint64_t v39;
    uint64_t v41;
    uint64_t v43;
    uint64_t v44;
    uint64_t v46;
    uint64_t v47;
    uint64_t v48;
    uint64_t v49;
    uint64_t v51;
    unsigned char *v53;
    uint64_t v54;
    uint64_t v55;
    uint64_t v56;
    uint64_t v58;
    uint64_t v59;
    uint64_t v60;
    unsigned char *v62;
    uint64_t v63;
    uint64_t v64;
    uint64_t v65;
    uint64_t v67;
    uint64_t v71;
    uint64_t v72;
    uint64_t v75;
    uint64_t v76;
    uint64_t v78;
    uint64_t v79;
    uint64_t v80;
    uint64_t v81;
    uint64_t v83;
    unsigned char *v85;
    uint64_t v86;
    uint64_t v87;
    uint64_t v88;
    uint64_t v90;
    uint64_t v91;
    uint64_t v92;
    unsigned char *v94;
    uint64_t v95;
    uint64_t v96;
    uint64_t v97;
    uint64_t v99;
    uint64_t v103;
    uint64_t t21;
    uint64_t t46;
    uint64_t t78;
    v1 = p0;
    v2 = p1;
    v3 = UINT64_C(0);
    v4 = (v2 == v3);
    if (v4) {
        goto b2;
    } else {
        goto b3;
    }
b2:
    v6 = UINT64_C(23);
    return v6;
b3:
    v8 = UINT64_C(0);
    v9 = UINT64_C(4096);
    if (v8 >= v9) exsrt_abortus(1);
    v11 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v8 * 1);
    v12 = exsi_norm_u(exsi_ld_n(v11 + 0, 1), 8);
    v13 = UINT64_C(47);
    v14 = (v12 == v13);
    if (v14) {
        goto b4;
    } else {
        goto b5;
    }
b4:
    v16 = UINT64_C(20);
    return v16;
b5:
    v18 = UINT64_C(0);
    v19 = UINT64_C(0);
    t46 = v18;
    t21 = v19;
    v46 = t46;
    v21 = t21;
    goto b6;
b6:
    v22 = (v21 < v2);
    if (v22) {
        goto b7;
    } else {
        goto b8;
    }
b7:
    v24 = UINT64_C(4096);
    if (v21 >= v24) exsrt_abortus(1);
    v26 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v21 * 1);
    v27 = exsi_norm_u(exsi_ld_n(v26 + 0, 1), 8);
    v28 = UINT64_C(32);
    v29 = (v27 < v28);
    if (v29) {
        goto b10;
    } else {
        goto b11;
    }
b8:
    v79 = exsi_sub_u(v2, v46, 64);
    v80 = UINT64_C(2);
    v81 = (v79 == v80);
    if (v81) {
        goto b24;
    } else {
        goto b25;
    }
b9:
    v75 = UINT64_C(1);
    v76 = v21 + v75;
    t46 = v78;
    t21 = v76;
    v46 = t46;
    v21 = t21;
    goto b6;
b10:
    v31 = UINT64_C(22);
    return v31;
b11:
    v33 = UINT64_C(127);
    v34 = (v27 == v33);
    if (v34) {
        goto b12;
    } else {
        goto b13;
    }
b12:
    v36 = UINT64_C(22);
    return v36;
b13:
    v38 = UINT64_C(92);
    v39 = (v27 == v38);
    if (v39) {
        goto b14;
    } else {
        goto b15;
    }
b14:
    v41 = UINT64_C(22);
    return v41;
b15:
    v43 = UINT64_C(47);
    v44 = (v27 == v43);
    if (v44) {
        goto b16;
    } else {
        t78 = v46;
        v78 = t78;
        goto b17;
    }
b16:
    v47 = exsi_sub_u(v21, v46, 64);
    v48 = UINT64_C(2);
    v49 = (v47 == v48);
    if (v49) {
        goto b18;
    } else {
        goto b19;
    }
b17:
    goto b9;
b18:
    v51 = UINT64_C(4096);
    if (v46 >= v51) exsrt_abortus(1);
    v53 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v46 * 1);
    v54 = exsi_norm_u(exsi_ld_n(v53 + 0, 1), 8);
    v55 = UINT64_C(46);
    v56 = (v54 == v55);
    if (v56) {
        goto b20;
    } else {
        goto b21;
    }
b19:
    v71 = UINT64_C(1);
    v72 = exsi_add_u(v21, v71, 64);
    t78 = v72;
    v78 = t78;
    goto b17;
b20:
    v58 = UINT64_C(1);
    v59 = exsi_add_u(v46, v58, 64);
    v60 = UINT64_C(4096);
    if (v59 >= v60) exsrt_abortus(1);
    v62 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v59 * 1);
    v63 = exsi_norm_u(exsi_ld_n(v62 + 0, 1), 8);
    v64 = UINT64_C(46);
    v65 = (v63 == v64);
    if (v65) {
        goto b22;
    } else {
        goto b23;
    }
b21:
    goto b19;
b22:
    v67 = UINT64_C(21);
    return v67;
b23:
    goto b21;
b24:
    v83 = UINT64_C(4096);
    if (v46 >= v83) exsrt_abortus(1);
    v85 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v46 * 1);
    v86 = exsi_norm_u(exsi_ld_n(v85 + 0, 1), 8);
    v87 = UINT64_C(46);
    v88 = (v86 == v87);
    if (v88) {
        goto b26;
    } else {
        goto b27;
    }
b25:
    v103 = UINT64_C(0);
    return v103;
b26:
    v90 = UINT64_C(1);
    v91 = exsi_add_u(v46, v90, 64);
    v92 = UINT64_C(4096);
    if (v91 >= v92) exsrt_abortus(1);
    v94 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v91 * 1);
    v95 = exsi_norm_u(exsi_ld_n(v94 + 0, 1), 8);
    v96 = UINT64_C(46);
    v97 = (v95 == v96);
    if (v97) {
        goto b28;
    } else {
        goto b29;
    }
b27:
    goto b25;
b28:
    v99 = UINT64_C(21);
    return v99;
b29:
    goto b27;
}

uint64_t exs_caput_iudica(unsigned char *p0, unsigned char *p1, uint64_t p2, uint64_t p3)
{
    unsigned char *v1;
    unsigned char *v2;
    uint64_t v3;
    uint64_t v4;
    uint64_t v5;
    uint64_t v6;
    uint64_t v7;
    uint64_t v9;
    uint64_t v10;
    uint64_t v12;
    unsigned char *v14;
    uint64_t v15;
    uint64_t v16;
    uint64_t v17;
    uint64_t v19;
    uint64_t v22;
    uint64_t v23;
    uint64_t v25;
    uint64_t v26;
    uint64_t v27;
    uint64_t v28;
    uint64_t v30;
    uint64_t v31;
    uint64_t v33;
    uint64_t v35;
    uint64_t v37;
    uint64_t v38;
    uint64_t v39;
    uint64_t v41;
    uint64_t v42;
    uint64_t v44;
    uint64_t v45;
    uint64_t v47;
    uint64_t v48;
    uint64_t v50;
    uint64_t v51;
    uint64_t v52;
    uint64_t v54;
    unsigned char *v56;
    uint64_t v57;
    uint64_t v58;
    uint64_t v59;
    uint64_t v62;
    unsigned char *v64;
    uint64_t v65;
    uint64_t v66;
    uint64_t v67;
    uint64_t v70;
    uint64_t v71;
    uint64_t v73;
    uint64_t v74;
    uint64_t v75;
    uint64_t v76;
    uint64_t v77;
    uint64_t v79;
    uint64_t v80;
    uint64_t v82;
    unsigned char *v84;
    uint64_t v85;
    uint64_t v86;
    uint64_t v87;
    uint64_t v89;
    uint64_t v91;
    uint64_t v92;
    uint64_t v94;
    uint64_t v96;
    uint64_t v97;
    uint64_t v98;
    uint64_t v99;
    uint64_t v100;
    uint64_t v101;
    uint64_t v102;
    uint64_t v104;
    uint64_t v105;
    uint64_t v107;
    uint64_t v108;
    unsigned char *v110;
    uint64_t v111;
    uint64_t v112;
    uint64_t v113;
    uint64_t v115;
    uint64_t v117;
    uint64_t v118;
    unsigned char *v120;
    uint64_t v121;
    uint64_t v122;
    uint64_t v123;
    uint64_t v125;
    uint64_t v127;
    uint64_t v129;
    uint64_t v131;
    uint64_t v132;
    unsigned char *v134;
    uint64_t v135;
    uint64_t v136;
    uint64_t v137;
    uint64_t v139;
    uint64_t v141;
    uint64_t v142;
    unsigned char *v144;
    uint64_t v145;
    uint64_t v146;
    uint64_t v147;
    uint64_t v149;
    uint64_t v151;
    uint64_t v152;
    unsigned char *v154;
    uint64_t v155;
    uint64_t v156;
    uint64_t v157;
    uint64_t v159;
    uint64_t v161;
    uint64_t v162;
    unsigned char *v164;
    uint64_t v165;
    uint64_t v166;
    uint64_t v167;
    uint64_t v169;
    uint64_t v171;
    uint64_t v172;
    unsigned char *v174;
    uint64_t v175;
    uint64_t v176;
    uint64_t v177;
    uint64_t v179;
    uint64_t v181;
    uint64_t v182;
    unsigned char *v184;
    uint64_t v185;
    uint64_t v186;
    uint64_t v187;
    uint64_t v189;
    uint64_t v191;
    uint64_t v192;
    unsigned char *v194;
    uint64_t v195;
    uint64_t v196;
    uint64_t v197;
    uint64_t v199;
    uint64_t v201;
    uint64_t v202;
    unsigned char *v204;
    uint64_t v205;
    uint64_t v206;
    uint64_t v207;
    uint64_t v209;
    uint64_t v211;
    uint64_t v212;
    uint64_t v213;
    uint64_t v214;
    uint64_t v215;
    uint64_t v217;
    uint64_t v219;
    uint64_t v220;
    uint64_t v221;
    uint64_t v222;
    uint64_t v223;
    uint64_t v225;
    uint64_t v227;
    uint64_t v228;
    uint64_t v229;
    uint64_t v230;
    uint64_t v231;
    uint64_t v233;
    uint64_t v235;
    uint64_t v236;
    uint64_t v237;
    uint64_t v238;
    uint64_t v239;
    uint64_t v241;
    uint64_t v243;
    uint64_t v244;
    unsigned char *v246;
    uint64_t v247;
    uint64_t v248;
    uint64_t v249;
    uint64_t v250;
    uint64_t v252;
    uint64_t v254;
    uint64_t v255;
    uint64_t v257;
    uint64_t v258;
    uint64_t v260;
    uint64_t v262;
    uint64_t v263;
    uint64_t v265;
    uint64_t v267;
    uint64_t v268;
    uint64_t v270;
    uint64_t v272;
    uint64_t v273;
    unsigned char *v275;
    uint64_t v276;
    uint64_t v277;
    uint64_t v278;
    uint64_t v280;
    uint64_t v282;
    uint64_t v283;
    unsigned char *v285;
    uint64_t v286;
    uint64_t v287;
    uint64_t v288;
    uint64_t v290;
    uint64_t v292;
    uint64_t v293;
    unsigned char *v295;
    uint64_t v296;
    uint64_t v297;
    uint64_t v298;
    uint64_t v300;
    uint64_t v302;
    uint64_t v303;
    unsigned char *v305;
    uint64_t v306;
    uint64_t v307;
    uint64_t v308;
    uint64_t v310;
    uint64_t v312;
    uint64_t v313;
    unsigned char *v315;
    uint64_t v316;
    uint64_t v317;
    uint64_t v318;
    uint64_t v320;
    uint64_t v322;
    uint64_t v323;
    unsigned char *v325;
    uint64_t v326;
    uint64_t v327;
    uint64_t v328;
    uint64_t v330;
    uint64_t v332;
    uint64_t v333;
    unsigned char *v335;
    uint64_t v336;
    uint64_t v337;
    uint64_t v338;
    uint64_t v340;
    uint64_t v342;
    uint64_t v343;
    unsigned char *v345;
    uint64_t v346;
    uint64_t v347;
    uint64_t v348;
    uint64_t v350;
    uint64_t v352;
    uint64_t v353;
    unsigned char *v355;
    uint64_t v356;
    uint64_t v357;
    uint64_t v358;
    uint64_t v360;
    uint64_t v362;
    uint64_t v363;
    unsigned char *v365;
    uint64_t v366;
    uint64_t v367;
    uint64_t v368;
    uint64_t v370;
    uint64_t v372;
    uint64_t v373;
    unsigned char *v375;
    uint64_t v376;
    uint64_t v377;
    uint64_t v378;
    uint64_t v380;
    uint64_t v382;
    uint64_t v383;
    unsigned char *v385;
    uint64_t v386;
    uint64_t v387;
    uint64_t v388;
    uint64_t v390;
    uint64_t v392;
    uint64_t v393;
    unsigned char *v395;
    uint64_t v396;
    uint64_t v397;
    uint64_t v398;
    uint64_t v400;
    uint64_t v402;
    uint64_t v403;
    unsigned char *v405;
    uint64_t v406;
    uint64_t v407;
    uint64_t v408;
    uint64_t v410;
    uint64_t v412;
    uint64_t v414;
    uint64_t v415;
    uint64_t v416;
    uint64_t v418;
    uint64_t v420;
    uint64_t v421;
    uint64_t v423;
    uint64_t v426;
    uint64_t v427;
    uint64_t v428;
    uint64_t v430;
    uint64_t v431;
    uint64_t v433;
    unsigned char *v436;
    uint64_t v437;
    uint64_t v438;
    uint64_t v440;
    uint64_t v441;
    uint64_t v442;
    unsigned char *v444;
    uint64_t v446;
    uint64_t v447;
    uint64_t v449;
    uint64_t v450;
    uint64_t v451;
    uint64_t v453;
    uint64_t v454;
    uint64_t v456;
    uint64_t v458;
    uint64_t v459;
    uint64_t v461;
    uint64_t v463;
    uint64_t v464;
    uint64_t v465;
    unsigned char *v467;
    uint64_t v468;
    uint64_t v469;
    uint64_t v470;
    uint64_t v472;
    uint64_t v474;
    uint64_t v475;
    uint64_t v476;
    uint64_t v478;
    uint64_t v479;
    uint64_t v481;
    unsigned char *v483;
    uint64_t v484;
    uint64_t v485;
    uint64_t v486;
    uint64_t v488;
    uint64_t v490;
    unsigned char *v492;
    uint64_t v493;
    uint64_t v494;
    unsigned char *v496;
    uint64_t v499;
    uint64_t v500;
    uint64_t v502;
    uint64_t v503;
    uint64_t v505;
    uint64_t v506;
    uint64_t v507;
    uint64_t v509;
    uint64_t v510;
    uint64_t v512;
    uint64_t v513;
    uint64_t v514;
    uint64_t v516;
    unsigned char *v518;
    uint64_t v519;
    uint64_t v520;
    uint64_t v521;
    uint64_t v523;
    uint64_t v525;
    unsigned char *v527;
    uint64_t v528;
    uint64_t v529;
    unsigned char *v531;
    uint64_t v533;
    uint64_t v534;
    uint64_t v535;
    uint64_t v539;
    uint64_t v540;
    uint64_t v542;
    uint64_t v543;
    uint64_t v544;
    uint64_t v545;
    uint64_t v547;
    uint64_t v548;
    uint64_t v549;
    uint64_t v550;
    uint64_t v553;
    uint64_t v554;
    uint64_t v555;
    unsigned char *v557;
    uint64_t v558;
    uint64_t v559;
    uint64_t v560;
    uint64_t v562;
    uint64_t v563;
    uint64_t v565;
    uint64_t v567;
    uint64_t v569;
    uint64_t v570;
    uint64_t v572;
    uint64_t v574;
    uint64_t t9;
    uint64_t t25;
    uint64_t t26;
    uint64_t t41;
    uint64_t t50;
    uint64_t t73;
    uint64_t t74;
    uint64_t t79;
    uint64_t t96;
    uint64_t t426;
    uint64_t t440;
    uint64_t t478;
    uint64_t t509;
    uint64_t t512;
    uint64_t t533;
    uint64_t t542;
    uint64_t t543;
    uint64_t t544;
    uint64_t t545;
    uint64_t t547;
    _Alignas(1) unsigned char s436[4096];
    v1 = p0;
    v2 = p1;
    v3 = p2;
    v4 = p3;
    v5 = UINT64_C(1);
    v6 = UINT64_C(0);
    v7 = UINT64_C(512);
    t25 = v5;
    t9 = v6;
    v25 = t25;
    v9 = t9;
    goto b2;
b2:
    v10 = (v9 < v7);
    if (v10) {
        goto b3;
    } else {
        goto b4;
    }
b3:
    v12 = UINT64_C(512);
    if (v9 >= v12) exsrt_abortus(1);
    v14 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v9 * 1);
    v15 = exsi_norm_u(exsi_ld_n(v14 + 0, 1), 8);
    v16 = UINT64_C(0);
    v17 = (v15 != v16);
    if (v17) {
        goto b6;
    } else {
        t26 = v25;
        v26 = t26;
        goto b7;
    }
b4:
    v27 = UINT64_C(1);
    v28 = (v25 == v27);
    if (v28) {
        goto b8;
    } else {
        goto b9;
    }
b5:
    v22 = UINT64_C(1);
    v23 = v9 + v22;
    t25 = v26;
    t9 = v23;
    v25 = t25;
    v9 = t9;
    goto b2;
b6:
    v19 = UINT64_C(0);
    t26 = v19;
    v26 = t26;
    goto b7;
b7:
    goto b5;
b8:
    v30 = UINT64_C(1);
    v31 = (v4 == v30);
    if (v31) {
        goto b10;
    } else {
        goto b11;
    }
b9:
    v37 = UINT64_C(0);
    v38 = UINT64_C(0);
    v39 = UINT64_C(512);
    t50 = v37;
    t41 = v38;
    v50 = t50;
    v41 = t41;
    goto b12;
b10:
    v33 = UINT64_C(25);
    return v33;
b11:
    v35 = UINT64_C(3);
    return v35;
b12:
    v42 = (v41 < v39);
    if (v42) {
        goto b13;
    } else {
        goto b14;
    }
b13:
    v44 = UINT64_C(148);
    v45 = (v41 >= v44);
    if (v45) {
        goto b16;
    } else {
        goto b17;
    }
b14:
    v75 = UINT64_C(0);
    v76 = UINT64_C(148);
    v77 = UINT64_C(154);
    t96 = v75;
    t79 = v76;
    v96 = t96;
    v79 = t79;
    goto b22;
b15:
    v70 = UINT64_C(1);
    v71 = v41 + v70;
    t50 = v73;
    t41 = v71;
    v50 = t50;
    v41 = t41;
    goto b12;
b16:
    v47 = UINT64_C(156);
    v48 = (v41 < v47);
    if (v48) {
        goto b18;
    } else {
        goto b19;
    }
b17:
    v62 = UINT64_C(512);
    if (v41 >= v62) exsrt_abortus(1);
    v64 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v41 * 1);
    v65 = exsi_norm_u(exsi_ld_n(v64 + 0, 1), 8);
    v66 = exsi_norm_u(v65, 8);
    v67 = exsi_add_u(v50, v66, 64);
    t73 = v67;
    v73 = t73;
    goto b21;
b18:
    v51 = UINT64_C(32);
    v52 = exsi_add_u(v50, v51, 64);
    t74 = v52;
    v74 = t74;
    goto b20;
b19:
    v54 = UINT64_C(512);
    if (v41 >= v54) exsrt_abortus(1);
    v56 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v41 * 1);
    v57 = exsi_norm_u(exsi_ld_n(v56 + 0, 1), 8);
    v58 = exsi_norm_u(v57, 8);
    v59 = exsi_add_u(v50, v58, 64);
    t74 = v59;
    v74 = t74;
    goto b20;
b20:
    t73 = v74;
    v73 = t73;
    goto b21;
b21:
    goto b15;
b22:
    v80 = (v79 < v77);
    if (v80) {
        goto b23;
    } else {
        goto b24;
    }
b23:
    v82 = UINT64_C(512);
    if (v79 >= v82) exsrt_abortus(1);
    v84 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v79 * 1);
    v85 = exsi_norm_u(exsi_ld_n(v84 + 0, 1), 8);
    v86 = UINT64_C(48);
    v87 = (v85 < v86);
    if (v87) {
        goto b26;
    } else {
        goto b27;
    }
b24:
    v107 = UINT64_C(154);
    v108 = UINT64_C(512);
    if (v107 >= v108) exsrt_abortus(1);
    v110 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v107 * 1);
    v111 = exsi_norm_u(exsi_ld_n(v110 + 0, 1), 8);
    v112 = UINT64_C(0);
    v113 = (v111 != v112);
    if (v113) {
        goto b30;
    } else {
        goto b31;
    }
b25:
    v104 = UINT64_C(1);
    v105 = v79 + v104;
    t96 = v102;
    t79 = v105;
    v96 = t96;
    v79 = t79;
    goto b22;
b26:
    v89 = UINT64_C(16);
    return v89;
b27:
    v91 = UINT64_C(55);
    v92 = (v85 > v91);
    if (v92) {
        goto b28;
    } else {
        goto b29;
    }
b28:
    v94 = UINT64_C(16);
    return v94;
b29:
    v97 = UINT64_C(3);
    v98 = exsi_shl_u(v96, v97, 64);
    v99 = UINT64_C(48);
    v100 = exsi_sub_u(v85, v99, 8);
    v101 = exsi_norm_u(v100, 8);
    v102 = v98 ^ v101;
    goto b25;
b30:
    v115 = UINT64_C(16);
    return v115;
b31:
    v117 = UINT64_C(155);
    v118 = UINT64_C(512);
    if (v117 >= v118) exsrt_abortus(1);
    v120 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v117 * 1);
    v121 = exsi_norm_u(exsi_ld_n(v120 + 0, 1), 8);
    v122 = UINT64_C(32);
    v123 = (v121 != v122);
    if (v123) {
        goto b32;
    } else {
        goto b33;
    }
b32:
    v125 = UINT64_C(16);
    return v125;
b33:
    v127 = (v96 != v50);
    if (v127) {
        goto b34;
    } else {
        goto b35;
    }
b34:
    v129 = UINT64_C(16);
    return v129;
b35:
    v131 = UINT64_C(257);
    v132 = UINT64_C(512);
    if (v131 >= v132) exsrt_abortus(1);
    v134 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v131 * 1);
    v135 = exsi_norm_u(exsi_ld_n(v134 + 0, 1), 8);
    v136 = UINT64_C(117);
    v137 = (v135 != v136);
    if (v137) {
        goto b36;
    } else {
        goto b37;
    }
b36:
    v139 = UINT64_C(17);
    return v139;
b37:
    v141 = UINT64_C(258);
    v142 = UINT64_C(512);
    if (v141 >= v142) exsrt_abortus(1);
    v144 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v141 * 1);
    v145 = exsi_norm_u(exsi_ld_n(v144 + 0, 1), 8);
    v146 = UINT64_C(115);
    v147 = (v145 != v146);
    if (v147) {
        goto b38;
    } else {
        goto b39;
    }
b38:
    v149 = UINT64_C(17);
    return v149;
b39:
    v151 = UINT64_C(259);
    v152 = UINT64_C(512);
    if (v151 >= v152) exsrt_abortus(1);
    v154 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v151 * 1);
    v155 = exsi_norm_u(exsi_ld_n(v154 + 0, 1), 8);
    v156 = UINT64_C(116);
    v157 = (v155 != v156);
    if (v157) {
        goto b40;
    } else {
        goto b41;
    }
b40:
    v159 = UINT64_C(17);
    return v159;
b41:
    v161 = UINT64_C(260);
    v162 = UINT64_C(512);
    if (v161 >= v162) exsrt_abortus(1);
    v164 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v161 * 1);
    v165 = exsi_norm_u(exsi_ld_n(v164 + 0, 1), 8);
    v166 = UINT64_C(97);
    v167 = (v165 != v166);
    if (v167) {
        goto b42;
    } else {
        goto b43;
    }
b42:
    v169 = UINT64_C(17);
    return v169;
b43:
    v171 = UINT64_C(261);
    v172 = UINT64_C(512);
    if (v171 >= v172) exsrt_abortus(1);
    v174 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v171 * 1);
    v175 = exsi_norm_u(exsi_ld_n(v174 + 0, 1), 8);
    v176 = UINT64_C(114);
    v177 = (v175 != v176);
    if (v177) {
        goto b44;
    } else {
        goto b45;
    }
b44:
    v179 = UINT64_C(17);
    return v179;
b45:
    v181 = UINT64_C(262);
    v182 = UINT64_C(512);
    if (v181 >= v182) exsrt_abortus(1);
    v184 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v181 * 1);
    v185 = exsi_norm_u(exsi_ld_n(v184 + 0, 1), 8);
    v186 = UINT64_C(32);
    v187 = (v185 != v186);
    if (v187) {
        goto b46;
    } else {
        goto b47;
    }
b46:
    v189 = UINT64_C(17);
    return v189;
b47:
    v191 = UINT64_C(263);
    v192 = UINT64_C(512);
    if (v191 >= v192) exsrt_abortus(1);
    v194 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v191 * 1);
    v195 = exsi_norm_u(exsi_ld_n(v194 + 0, 1), 8);
    v196 = UINT64_C(32);
    v197 = (v195 != v196);
    if (v197) {
        goto b48;
    } else {
        goto b49;
    }
b48:
    v199 = UINT64_C(17);
    return v199;
b49:
    v201 = UINT64_C(264);
    v202 = UINT64_C(512);
    if (v201 >= v202) exsrt_abortus(1);
    v204 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v201 * 1);
    v205 = exsi_norm_u(exsi_ld_n(v204 + 0, 1), 8);
    v206 = UINT64_C(0);
    v207 = (v205 != v206);
    if (v207) {
        goto b50;
    } else {
        goto b51;
    }
b50:
    v209 = UINT64_C(17);
    return v209;
b51:
    v211 = UINT64_C(100);
    v212 = UINT64_C(8);
    v213 = exs_octalis(v1, v211, v212);
    v214 = UINT64_C(0);
    v215 = (v213 == v214);
    if (v215) {
        goto b52;
    } else {
        goto b53;
    }
b52:
    v217 = UINT64_C(27);
    return v217;
b53:
    v219 = UINT64_C(108);
    v220 = UINT64_C(8);
    v221 = exs_octalis(v1, v219, v220);
    v222 = UINT64_C(0);
    v223 = (v221 == v222);
    if (v223) {
        goto b54;
    } else {
        goto b55;
    }
b54:
    v225 = UINT64_C(27);
    return v225;
b55:
    v227 = UINT64_C(116);
    v228 = UINT64_C(8);
    v229 = exs_octalis(v1, v227, v228);
    v230 = UINT64_C(0);
    v231 = (v229 == v230);
    if (v231) {
        goto b56;
    } else {
        goto b57;
    }
b56:
    v233 = UINT64_C(27);
    return v233;
b57:
    v235 = UINT64_C(136);
    v236 = UINT64_C(12);
    v237 = exs_octalis(v1, v235, v236);
    v238 = UINT64_C(0);
    v239 = (v237 == v238);
    if (v239) {
        goto b58;
    } else {
        goto b59;
    }
b58:
    v241 = UINT64_C(27);
    return v241;
b59:
    v243 = UINT64_C(156);
    v244 = UINT64_C(512);
    if (v243 >= v244) exsrt_abortus(1);
    v246 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v243 * 1);
    v247 = exsi_norm_u(exsi_ld_n(v246 + 0, 1), 8);
    v248 = exs_magnitudo(v1);
    v249 = UINT64_C(18446744073709551615);
    v250 = (v248 == v249);
    if (v250) {
        goto b60;
    } else {
        goto b61;
    }
b60:
    v252 = UINT64_C(19);
    return v252;
b61:
    v254 = UINT64_C(76);
    v255 = (v247 == v254);
    if (v255) {
        goto b62;
    } else {
        goto b63;
    }
b62:
    v257 = UINT64_C(1);
    v258 = (v4 == v257);
    if (v258) {
        goto b64;
    } else {
        goto b65;
    }
b63:
    v414 = UINT64_C(0);
    v415 = UINT64_C(53);
    v416 = (v247 == v415);
    if (v416) {
        goto b98;
    } else {
        goto b99;
    }
b64:
    v260 = UINT64_C(24);
    return v260;
b65:
    v262 = UINT64_C(0);
    v263 = (v248 == v262);
    if (v263) {
        goto b66;
    } else {
        goto b67;
    }
b66:
    v265 = UINT64_C(24);
    return v265;
b67:
    v267 = UINT64_C(4096);
    v268 = (v248 > v267);
    if (v268) {
        goto b68;
    } else {
        goto b69;
    }
b68:
    v270 = UINT64_C(24);
    return v270;
b69:
    v272 = UINT64_C(0);
    v273 = UINT64_C(512);
    if (v272 >= v273) exsrt_abortus(1);
    v275 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v272 * 1);
    v276 = exsi_norm_u(exsi_ld_n(v275 + 0, 1), 8);
    v277 = UINT64_C(46);
    v278 = (v276 != v277);
    if (v278) {
        goto b70;
    } else {
        goto b71;
    }
b70:
    v280 = UINT64_C(24);
    return v280;
b71:
    v282 = UINT64_C(1);
    v283 = UINT64_C(512);
    if (v282 >= v283) exsrt_abortus(1);
    v285 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v282 * 1);
    v286 = exsi_norm_u(exsi_ld_n(v285 + 0, 1), 8);
    v287 = UINT64_C(47);
    v288 = (v286 != v287);
    if (v288) {
        goto b72;
    } else {
        goto b73;
    }
b72:
    v290 = UINT64_C(24);
    return v290;
b73:
    v292 = UINT64_C(2);
    v293 = UINT64_C(512);
    if (v292 >= v293) exsrt_abortus(1);
    v295 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v292 * 1);
    v296 = exsi_norm_u(exsi_ld_n(v295 + 0, 1), 8);
    v297 = UINT64_C(46);
    v298 = (v296 != v297);
    if (v298) {
        goto b74;
    } else {
        goto b75;
    }
b74:
    v300 = UINT64_C(24);
    return v300;
b75:
    v302 = UINT64_C(3);
    v303 = UINT64_C(512);
    if (v302 >= v303) exsrt_abortus(1);
    v305 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v302 * 1);
    v306 = exsi_norm_u(exsi_ld_n(v305 + 0, 1), 8);
    v307 = UINT64_C(47);
    v308 = (v306 != v307);
    if (v308) {
        goto b76;
    } else {
        goto b77;
    }
b76:
    v310 = UINT64_C(24);
    return v310;
b77:
    v312 = UINT64_C(4);
    v313 = UINT64_C(512);
    if (v312 >= v313) exsrt_abortus(1);
    v315 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v312 * 1);
    v316 = exsi_norm_u(exsi_ld_n(v315 + 0, 1), 8);
    v317 = UINT64_C(64);
    v318 = (v316 != v317);
    if (v318) {
        goto b78;
    } else {
        goto b79;
    }
b78:
    v320 = UINT64_C(24);
    return v320;
b79:
    v322 = UINT64_C(5);
    v323 = UINT64_C(512);
    if (v322 >= v323) exsrt_abortus(1);
    v325 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v322 * 1);
    v326 = exsi_norm_u(exsi_ld_n(v325 + 0, 1), 8);
    v327 = UINT64_C(76);
    v328 = (v326 != v327);
    if (v328) {
        goto b80;
    } else {
        goto b81;
    }
b80:
    v330 = UINT64_C(24);
    return v330;
b81:
    v332 = UINT64_C(6);
    v333 = UINT64_C(512);
    if (v332 >= v333) exsrt_abortus(1);
    v335 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v332 * 1);
    v336 = exsi_norm_u(exsi_ld_n(v335 + 0, 1), 8);
    v337 = UINT64_C(111);
    v338 = (v336 != v337);
    if (v338) {
        goto b82;
    } else {
        goto b83;
    }
b82:
    v340 = UINT64_C(24);
    return v340;
b83:
    v342 = UINT64_C(7);
    v343 = UINT64_C(512);
    if (v342 >= v343) exsrt_abortus(1);
    v345 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v342 * 1);
    v346 = exsi_norm_u(exsi_ld_n(v345 + 0, 1), 8);
    v347 = UINT64_C(110);
    v348 = (v346 != v347);
    if (v348) {
        goto b84;
    } else {
        goto b85;
    }
b84:
    v350 = UINT64_C(24);
    return v350;
b85:
    v352 = UINT64_C(8);
    v353 = UINT64_C(512);
    if (v352 >= v353) exsrt_abortus(1);
    v355 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v352 * 1);
    v356 = exsi_norm_u(exsi_ld_n(v355 + 0, 1), 8);
    v357 = UINT64_C(103);
    v358 = (v356 != v357);
    if (v358) {
        goto b86;
    } else {
        goto b87;
    }
b86:
    v360 = UINT64_C(24);
    return v360;
b87:
    v362 = UINT64_C(9);
    v363 = UINT64_C(512);
    if (v362 >= v363) exsrt_abortus(1);
    v365 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v362 * 1);
    v366 = exsi_norm_u(exsi_ld_n(v365 + 0, 1), 8);
    v367 = UINT64_C(76);
    v368 = (v366 != v367);
    if (v368) {
        goto b88;
    } else {
        goto b89;
    }
b88:
    v370 = UINT64_C(24);
    return v370;
b89:
    v372 = UINT64_C(10);
    v373 = UINT64_C(512);
    if (v372 >= v373) exsrt_abortus(1);
    v375 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v372 * 1);
    v376 = exsi_norm_u(exsi_ld_n(v375 + 0, 1), 8);
    v377 = UINT64_C(105);
    v378 = (v376 != v377);
    if (v378) {
        goto b90;
    } else {
        goto b91;
    }
b90:
    v380 = UINT64_C(24);
    return v380;
b91:
    v382 = UINT64_C(11);
    v383 = UINT64_C(512);
    if (v382 >= v383) exsrt_abortus(1);
    v385 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v382 * 1);
    v386 = exsi_norm_u(exsi_ld_n(v385 + 0, 1), 8);
    v387 = UINT64_C(110);
    v388 = (v386 != v387);
    if (v388) {
        goto b92;
    } else {
        goto b93;
    }
b92:
    v390 = UINT64_C(24);
    return v390;
b93:
    v392 = UINT64_C(12);
    v393 = UINT64_C(512);
    if (v392 >= v393) exsrt_abortus(1);
    v395 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v392 * 1);
    v396 = exsi_norm_u(exsi_ld_n(v395 + 0, 1), 8);
    v397 = UINT64_C(107);
    v398 = (v396 != v397);
    if (v398) {
        goto b94;
    } else {
        goto b95;
    }
b94:
    v400 = UINT64_C(24);
    return v400;
b95:
    v402 = UINT64_C(13);
    v403 = UINT64_C(512);
    if (v402 >= v403) exsrt_abortus(1);
    v405 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v402 * 1);
    v406 = exsi_norm_u(exsi_ld_n(v405 + 0, 1), 8);
    v407 = UINT64_C(0);
    v408 = (v406 != v407);
    if (v408) {
        goto b96;
    } else {
        goto b97;
    }
b96:
    v410 = UINT64_C(24);
    return v410;
b97:
    v412 = UINT64_C(2);
    return v412;
b98:
    v418 = UINT64_C(1);
    t426 = v418;
    v426 = t426;
    goto b100;
b99:
    v420 = UINT64_C(48);
    v421 = (v247 != v420);
    if (v421) {
        goto b101;
    } else {
        goto b102;
    }
b100:
    v427 = UINT64_C(1);
    v428 = (v426 == v427);
    if (v428) {
        goto b103;
    } else {
        goto b104;
    }
b101:
    v423 = UINT64_C(18);
    return v423;
b102:
    t426 = v414;
    v426 = t426;
    goto b100;
b103:
    v430 = UINT64_C(0);
    v431 = (v248 != v430);
    if (v431) {
        goto b105;
    } else {
        goto b106;
    }
b104:
    v436 = s436;
    v437 = UINT64_C(0);
    v438 = UINT64_C(0);
    t440 = v438;
    v440 = t440;
    goto b107;
b105:
    v433 = UINT64_C(26);
    return v433;
b106:
    goto b104;
b107:
    v441 = UINT64_C(4096);
    v442 = (v440 < v441);
    if (v442) {
        goto b108;
    } else {
        goto b109;
    }
b108:
    v444 = (unsigned char *)((uintptr_t)v436 + (uintptr_t)v440 * 1);
    exsi_st_n(v444 + 0, 1, v437);
    v446 = UINT64_C(1);
    v447 = v440 + v446;
    t440 = v447;
    v440 = t440;
    goto b107;
b109:
    v449 = UINT64_C(0);
    v450 = UINT64_C(1);
    v451 = (v4 == v450);
    if (v451) {
        goto b110;
    } else {
        goto b111;
    }
b110:
    v453 = UINT64_C(0);
    v454 = (v3 == v453);
    if (v454) {
        goto b112;
    } else {
        goto b113;
    }
b111:
    v505 = UINT64_C(0);
    v506 = UINT64_C(0);
    v507 = UINT64_C(100);
    t533 = v449;
    t512 = v505;
    t509 = v506;
    v533 = t533;
    v512 = t512;
    v509 = t509;
    goto b125;
b112:
    v456 = UINT64_C(24);
    return v456;
b113:
    v458 = UINT64_C(4096);
    v459 = (v3 > v458);
    if (v459) {
        goto b114;
    } else {
        goto b115;
    }
b114:
    v461 = UINT64_C(24);
    return v461;
b115:
    v463 = UINT64_C(1);
    v464 = exsi_sub_u(v3, v463, 64);
    v465 = UINT64_C(4096);
    if (v464 >= v465) exsrt_abortus(1);
    v467 = (unsigned char *)((uintptr_t)v2 + (uintptr_t)v464 * 1);
    v468 = exsi_norm_u(exsi_ld_n(v467 + 0, 1), 8);
    v469 = UINT64_C(0);
    v470 = (v468 != v469);
    if (v470) {
        goto b116;
    } else {
        goto b117;
    }
b116:
    v472 = UINT64_C(24);
    return v472;
b117:
    v474 = UINT64_C(0);
    v475 = UINT64_C(1);
    v476 = exsi_sub_u(v3, v475, 64);
    t478 = v474;
    v478 = t478;
    goto b118;
b118:
    v479 = (v478 < v476);
    if (v479) {
        goto b119;
    } else {
        goto b120;
    }
b119:
    v481 = UINT64_C(4096);
    if (v478 >= v481) exsrt_abortus(1);
    v483 = (unsigned char *)((uintptr_t)v2 + (uintptr_t)v478 * 1);
    v484 = exsi_norm_u(exsi_ld_n(v483 + 0, 1), 8);
    v485 = UINT64_C(0);
    v486 = (v484 == v485);
    if (v486) {
        goto b122;
    } else {
        goto b123;
    }
b120:
    v502 = UINT64_C(1);
    v503 = exsi_sub_u(v3, v502, 64);
    t547 = v503;
    v547 = t547;
    goto b124;
b121:
    v499 = UINT64_C(1);
    v500 = v478 + v499;
    t478 = v500;
    v478 = t478;
    goto b118;
b122:
    v488 = UINT64_C(24);
    return v488;
b123:
    v490 = UINT64_C(4096);
    if (v478 >= v490) exsrt_abortus(1);
    v492 = (unsigned char *)((uintptr_t)v2 + (uintptr_t)v478 * 1);
    v493 = exsi_norm_u(exsi_ld_n(v492 + 0, 1), 8);
    v494 = UINT64_C(4096);
    if (v478 >= v494) exsrt_abortus(1);
    v496 = (unsigned char *)((uintptr_t)v436 + (uintptr_t)v478 * 1);
    exsi_st_n(v496 + 0, 1, v493);
    goto b121;
b124:
    v548 = exs_nomen_iudica(v436, v547);
    v549 = UINT64_C(0);
    v550 = (v548 != v549);
    if (v550) {
        goto b134;
    } else {
        goto b135;
    }
b125:
    v510 = (v509 < v507);
    if (v510) {
        goto b126;
    } else {
        goto b127;
    }
b126:
    v513 = UINT64_C(0);
    v514 = (v512 == v513);
    if (v514) {
        goto b129;
    } else {
        t544 = v533;
        t542 = v512;
        v544 = t544;
        v542 = t542;
        goto b130;
    }
b127:
    t547 = v533;
    v547 = t547;
    goto b124;
b128:
    v539 = UINT64_C(1);
    v540 = v509 + v539;
    t533 = v544;
    t512 = v542;
    t509 = v540;
    v533 = t533;
    v512 = t512;
    v509 = t509;
    goto b125;
b129:
    v516 = UINT64_C(512);
    if (v509 >= v516) exsrt_abortus(1);
    v518 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v509 * 1);
    v519 = exsi_norm_u(exsi_ld_n(v518 + 0, 1), 8);
    v520 = UINT64_C(0);
    v521 = (v519 == v520);
    if (v521) {
        goto b131;
    } else {
        goto b132;
    }
b130:
    goto b128;
b131:
    v523 = UINT64_C(1);
    t545 = v533;
    t543 = v523;
    v545 = t545;
    v543 = t543;
    goto b133;
b132:
    v525 = UINT64_C(512);
    if (v509 >= v525) exsrt_abortus(1);
    v527 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v509 * 1);
    v528 = exsi_norm_u(exsi_ld_n(v527 + 0, 1), 8);
    v529 = UINT64_C(4096);
    if (v509 >= v529) exsrt_abortus(1);
    v531 = (unsigned char *)((uintptr_t)v436 + (uintptr_t)v509 * 1);
    exsi_st_n(v531 + 0, 1, v528);
    v534 = UINT64_C(1);
    v535 = exsi_add_u(v533, v534, 64);
    t545 = v535;
    t543 = v512;
    v545 = t545;
    v543 = t543;
    goto b133;
b133:
    t544 = v545;
    t542 = v543;
    v544 = t544;
    v542 = t542;
    goto b130;
b134:
    return v548;
b135:
    v553 = UINT64_C(1);
    v554 = exsi_sub_u(v547, v553, 64);
    v555 = UINT64_C(4096);
    if (v554 >= v555) exsrt_abortus(1);
    v557 = (unsigned char *)((uintptr_t)v436 + (uintptr_t)v554 * 1);
    v558 = exsi_norm_u(exsi_ld_n(v557 + 0, 1), 8);
    v559 = UINT64_C(47);
    v560 = (v558 == v559);
    if (v560) {
        goto b136;
    } else {
        goto b137;
    }
b136:
    v562 = UINT64_C(0);
    v563 = (v426 == v562);
    if (v563) {
        goto b138;
    } else {
        goto b139;
    }
b137:
    v569 = UINT64_C(1);
    v570 = (v426 == v569);
    if (v570) {
        goto b140;
    } else {
        goto b141;
    }
b138:
    v565 = UINT64_C(26);
    return v565;
b139:
    v567 = UINT64_C(1);
    return v567;
b140:
    v572 = UINT64_C(26);
    return v572;
b141:
    v574 = UINT64_C(0);
    return v574;
}

