[package]
name = "streamdb"
version = "0.1.0"
edition = "2021"
description = "A reverse Trie index key-value database for path-based queries with prefix searches."
license = "LGPL-3.0"
repository = "https://github.com/xai/streamdb"

[dependencies]
im = "15.1.0"
okaywal = "0.2.1"
ring = { version = "0.17.8", optional = true }
tokio = { version = "1.40.0", features = ["sync", "rt"] }
ffi-support = "0.4.4"
bincode = "1.3.3"
uuid = { version = "1.10.0", features = ["v4"] }
crc = "3.2.1"
memmap2 = "0.9.4"
byteorder = "1.5.0"
parking_lot = "0.12.3"
lru = "0.12.4"
snappy = "0.6.0"
futures = "0.3.30"
log = "0.4.21"
serde = { version = "1.0.197", features = ["derive"] }

[dev-dependencies]
proptest = "1.5.0"
criterion = "0.5.1"
sled = "0.34.7"

[features]
encryption = ["ring"]
wasm = []
