#define EXS_NEED_FLOAT 0
/* exsecutor: reach backend */
/* Generated by exsc --emitte c. Do not edit: the text of this prologue is a
 * function of exsc's own bytes (docs/design/c-backend.md D5), the way the
 * reference backend's prelude blob is. */
#include <stdint.h>
#include <limits.h>
#ifndef EXS_NEED_FLOAT
#define EXS_NEED_FLOAT 1
#endif
#if EXS_NEED_FLOAT
#include <float.h>
#endif

#if !defined(__GNUC__) && !defined(__clang__)
# error "exsecutor: the emitted C is C11 plus a GCC/Clang extension set (ADR 0012)"
#endif
#if !defined(__BYTE_ORDER__) || !defined(__ORDER_LITTLE_ENDIAN__) || !defined(__ORDER_BIG_ENDIAN__)
# error "exsecutor: __BYTE_ORDER__ is required to select the nativus helpers"
#endif
#if defined(__FAST_MATH__)
# error "exsecutor: -ffast-math is refused (spec 5.4)"
#endif
#if defined(__FINITE_MATH_ONLY__) && __FINITE_MATH_ONLY__
# error "exsecutor: -ffinite-math-only is refused (spec 5.4)"
#endif

#if EXS_NEED_FLOAT
/* ---- IEEE binary32/64: the numeric subset's one target (spec 5.4) -------
 * ADR 0012's rung (b), spelled with <float.h> exactly as ADR 0012 names it
 * -- freestanding-safe, unlike __STDC_IEC_559__ (which a freestanding
 * implementation may define without honouring). `float` is binary32 and
 * `double` binary64, and no operation gains precision: FLT_EVAL_METHOD 0
 * is what makes `float op float` a FLOAT operation in C rather than a
 * double one (C's usual arithmetic conversions leave the type alone, but
 * only an evaluation method of 0 leaves the RESULT alone). Subnormals are
 * values (subnormales conservata); where C11's <float.h> stays silent
 * about them (the *_HAS_SUBNORM macros are optional before C23) the
 * runtime's MXCSR/FPCR image is what enforces it -- FTZ and DAZ clear,
 * which the reference prelude's 0x1F80 image also carries. */
_Static_assert(FLT_RADIX == 2, "exsecutor: the numeric subset is IEEE binary32/64 (spec 5.4)");
_Static_assert(FLT_MANT_DIG == 24 && DBL_MANT_DIG == 53,
               "exsecutor: float is binary32 and double is binary64");
_Static_assert(FLT_MAX_EXP == 128 && DBL_MAX_EXP == 1024,
               "exsecutor: binary32/64 exponent widths");
#if FLT_EVAL_METHOD != 0
# error "exsecutor: FLT_EVAL_METHOD must be 0 (spec 5.4: one rounding, in the operands' own width)"
#endif
#if defined(FLT_HAS_SUBNORM) && FLT_HAS_SUBNORM != 1
# error "exsecutor: float subnormals must be preserved (spec 5.4 subnormales conservata)"
#endif
#if defined(DBL_HAS_SUBNORM) && DBL_HAS_SUBNORM != 1
# error "exsecutor: double subnormals must be preserved (spec 5.4 subnormales conservata)"
#endif

/* Contraction (spec 5.4 contractio explicita; ADR 0012 problem 1). One IR
 * op is one C statement, so no emitted statement ever holds a
 * multiply-and-add tree to contract -- `fma` is the only contraction the
 * language has, it is refused by name in both backends, and this pragma is
 * the belt to that brace. `#pragma STDC FP_CONTRACT OFF` is NOT emitted:
 * measured to do nothing in both compilers, and GCC warns about it under
 * -Wall (c-backend.md D3, finding 12). Clang has nothing that works from
 * inside the source (`#pragma clang fp contract(off)` does not override a
 * command-line -ffp-contract=fast), so nothing is said to it and nothing
 * is lied about. */
#if defined(__GNUC__) && !defined(__clang__)
# pragma GCC optimize("fp-contract=off")
#endif
#endif /* EXS_NEED_FLOAT */

_Static_assert(CHAR_BIT == 8, "exsecutor: CHAR_BIT must be 8");
_Static_assert((-1 & 3) == 3, "exsecutor: two's complement");
_Static_assert(sizeof(unsigned) * CHAR_BIT >= 32, "exsecutor: unsigned holds a byte and a shift");

/* The trap hook: the ONE symbol a library-mode unit imports. Whoever links
 * it supplies the body (c-backend.md D1). Kinds are prelude/README.md's:
 * 1 numeric (overflow, a shift count past the width, a failed chk),
 * 5 terminus. */
_Noreturn void exsrt_abortus(unsigned kind);

/* Every integer value of any uN or iN is held in a uint64_t in canonical
 * form (ssa-ir.md 2.2): a uN zero-extended, an iN sign-extended. Every
 * helper assumes canonical inputs and returns a canonical result. All
 * arithmetic is on uint64_t, whose overflow C defines as modular, so no
 * emitted operation is undefined and -fwrapv / -ftrapv are irrelevant. */
static inline uint64_t exsi_mask(unsigned n)
{ return n == 64 ? UINT64_MAX : (UINT64_C(1) << n) - 1; }
static inline uint64_t exsi_norm_u(uint64_t x, unsigned n)
{ return x & exsi_mask(n); }
static inline uint64_t exsi_norm_i(uint64_t x, unsigned n)
{ uint64_t s = UINT64_C(1) << (n - 1); return ((x & exsi_mask(n)) ^ s) - s; }

#if EXS_NEED_FLOAT
/* Floats from their bits -- `fconst`'s round-trip. `fconst F bits` carries
 * the RAW bit pattern (ssa-ir.md 2.3: bits, never decimal text) and it must
 * come back exactly: payload bits included (a NaN's payload survives fneg),
 * sign included (-0.0 is a different constant from 0.0), subnormal bits
 * included (subnormales conservata). A C floating literal cannot spell any
 * of that -- a hex floating literal for an out-of-range pattern loses the
 * NaN payload and the quiet bit -- so the pattern is written as an integer
 * constant and re-read through the object representation:
 * __builtin_memcpy, the GCC-recommended bit-cast, already measured and on
 * D3's extension list for `copy n` (c-backend.md finding 13). Assumes a
 * float's byte order is the integer byte order -- true of every target in
 * scope: x86_64, riscv64 and mips64 are each uniform in their byte order,
 * which is what the emitted `exsi_ld_n` selection also assumes. */
static inline float exsi_f32_from_bits(uint32_t b)
{ float f; __builtin_memcpy(&f, &b, sizeof f); return f; }
static inline double exsi_f64_from_bits(uint64_t b)
{ double d; __builtin_memcpy(&d, &b, sizeof d); return d; }

/* The way back, for `store F`: the float's bit pattern as the integer the
 * byte-store helpers carry. Same bit-cast, same assumption a few lines
 * above (a float's byte order is the integer byte order) -- the round trip
 * store-then-load is the identity on every --hospes row, which is all
 * memory consistency asks of a bit pattern with no numeric reading. */
static inline uint32_t exsi_bits_from_f32(float f)
{ uint32_t b; __builtin_memcpy(&b, &f, sizeof b); return b; }
static inline uint64_t exsi_bits_from_f64(double d)
{ uint64_t b; __builtin_memcpy(&b, &d, sizeof b); return b; }

/* The vector float group (spec 5.4's vf32.N/vf64.N; ssa-ir.md 2.2: N lanes
 * of binary32/binary64, N in {2,4,8}), as C's vector_size extension -- one
 * of the GCC/Clang extensions ADR 0012's set already carries. One IR
 * vadd/vsub/vmul/vdiv is one C statement on the whole vector (the one
 * op-per-statement rule), and the operator's elementwise lowering is the
 * ONE IEEE rounding per lane the reference's packed addps/addpd carries:
 * GCC and Clang both lower vector_size arithmetic elementwise on x86-64
 * and soft-lower it on the mips64-none cross target, which is what keeps
 * cross=yes alive for this wave. NO intrinsics and no <emmintrin.h>-family
 * header: those spellings do not exist on the cross target. */
typedef float exs_vf32_2 __attribute__((vector_size(8)));
typedef float exs_vf32_4 __attribute__((vector_size(16)));
typedef float exs_vf32_8 __attribute__((vector_size(32)));
typedef double exs_vf64_2 __attribute__((vector_size(16)));
typedef double exs_vf64_4 __attribute__((vector_size(32)));
typedef double exs_vf64_8 __attribute__((vector_size(64)));
/* The N = 8 helpers carry 32/64-byte vectors, and both compilers note at
 * their definitions (GCC) or call sites (Clang) that passing such a vector
 * without AVX enabled "changes the ABI" (-Wpsabi). That warning is a
 * statement about TWO translation units compiled with different -m flags
 * sharing a function boundary -- and no boundary here carries a vector:
 * the helpers are `static inline` inside the single emitted unit, and the
 * unit's one imported/exported symbol (exs_initium's unsigned char *) is a
 * scalar. The note is noise for this blob and is switched off for it, the
 * way -Wno-unused-function is for the rest of it (recorded, not hidden). */
#if defined(__clang__)
# pragma clang diagnostic ignored "-Wpsabi"
#elif defined(__GNUC__)
# pragma GCC diagnostic ignored "-Wpsabi"
#endif
_Static_assert(sizeof(exs_vf32_2) == 8 && sizeof(exs_vf32_4) == 16 &&
               sizeof(exs_vf32_8) == 32,
               "exsecutor: a vf32.N is N binary32 lanes, packed (spec 5.4)");
_Static_assert(sizeof(exs_vf64_2) == 16 && sizeof(exs_vf64_4) == 32 &&
               sizeof(exs_vf64_8) == 64,
               "exsecutor: a vf64.N is N binary64 lanes, packed (spec 5.4)");

/* A vector in memory is its lanes' raw IEEE images, back to back in
 * subscript order, each element in the target's byte order -- the same
 * assumption the scalar helpers above name, so the nativus round trip is
 * the identity on every --hospes row. The load/store helpers are memcpy
 * bit baggage exactly the way the scalar float path's from_bits/bits_from
 * helpers are: no lane is read numerically on the path, so a NaN payload,
 * -0.0's sign and a subnormal's bits survive every copy (subnormales
 * conservata). */
static inline exs_vf32_2 exsi_ld_vf32_2(const unsigned char *p)
{ exs_vf32_2 v; __builtin_memcpy(&v, p, sizeof v); return v; }
static inline exs_vf32_4 exsi_ld_vf32_4(const unsigned char *p)
{ exs_vf32_4 v; __builtin_memcpy(&v, p, sizeof v); return v; }
static inline exs_vf32_8 exsi_ld_vf32_8(const unsigned char *p)
{ exs_vf32_8 v; __builtin_memcpy(&v, p, sizeof v); return v; }
static inline exs_vf64_2 exsi_ld_vf64_2(const unsigned char *p)
{ exs_vf64_2 v; __builtin_memcpy(&v, p, sizeof v); return v; }
static inline exs_vf64_4 exsi_ld_vf64_4(const unsigned char *p)
{ exs_vf64_4 v; __builtin_memcpy(&v, p, sizeof v); return v; }
static inline exs_vf64_8 exsi_ld_vf64_8(const unsigned char *p)
{ exs_vf64_8 v; __builtin_memcpy(&v, p, sizeof v); return v; }
static inline void exsi_st_vf32_2(unsigned char *p, exs_vf32_2 v)
{ __builtin_memcpy(p, &v, sizeof v); }
static inline void exsi_st_vf32_4(unsigned char *p, exs_vf32_4 v)
{ __builtin_memcpy(p, &v, sizeof v); }
static inline void exsi_st_vf32_8(unsigned char *p, exs_vf32_8 v)
{ __builtin_memcpy(p, &v, sizeof v); }
static inline void exsi_st_vf64_2(unsigned char *p, exs_vf64_2 v)
{ __builtin_memcpy(p, &v, sizeof v); }
static inline void exsi_st_vf64_4(unsigned char *p, exs_vf64_4 v)
{ __builtin_memcpy(p, &v, sizeof v); }
static inline void exsi_st_vf64_8(unsigned char *p, exs_vf64_8 v)
{ __builtin_memcpy(p, &v, sizeof v); }

/* itof from a signed integer's canonical bits. The carrier holds an iN
 * sign-extended (ssa-ir.md 2.2), so the two's-complement value IS the bit
 * pattern -- but C leaves a uint64_t -> int64_t conversion that does not
 * fit IMPLEMENTATION-DEFINED, a fact this prologue asserts nowhere and
 * refuses to rely on, so the bits are re-read as int64_t exactly the way
 * fconst re-reads a pattern as a float. The signed type appears here and
 * nowhere else: this is a conversion into a float, not arithmetic, and the
 * one-op-per-statement rule keeps it out of any expression a compiler
 * could contract. */
static inline int64_t exsi_i64_from_bits(uint64_t b)
{ int64_t s; __builtin_memcpy(&s, &b, sizeof s); return s; }

#endif /* EXS_NEED_FLOAT */

static inline uint64_t exsi_add_u(uint64_t a, uint64_t b, unsigned n)
{ uint64_t t = a + b;
  if (n == 64 ? t < a : t > exsi_mask(n)) exsrt_abortus(1);
  return t; }
static inline uint64_t exsi_add_i(uint64_t a, uint64_t b, unsigned n)
{ uint64_t t = a + b;
  if (n == 64 ? ((((a ^ t) & (b ^ t)) >> 63) != 0) : exsi_norm_i(t, n) != t)
    exsrt_abortus(1);
  return t; }
static inline uint64_t exsi_sub_u(uint64_t a, uint64_t b, unsigned n)
{ uint64_t t = a - b;
  if (n == 64 ? a < b : t > exsi_mask(n)) exsrt_abortus(1);
  return t; }
static inline uint64_t exsi_sub_i(uint64_t a, uint64_t b, unsigned n)
{ uint64_t t = a - b;
  if (n == 64 ? ((((a ^ b) & (a ^ t)) >> 63) != 0) : exsi_norm_i(t, n) != t)
    exsrt_abortus(1);
  return t; }
/* mul checks by DIVISION at every width rather than in a wider type: GCC
 * provides __int128 only where __SIZEOF_INT128__ is defined, which excludes
 * 32-bit-pointer targets such as o64 (c-backend.md finding 5). b > M / a is
 * exact. */
static inline uint64_t exsi_mul_u(uint64_t a, uint64_t b, unsigned n)
{ if (n <= 32) { uint64_t t = a * b; if (t > exsi_mask(n)) exsrt_abortus(1); return t; }
  if (a != 0 && b > exsi_mask(n) / a) exsrt_abortus(1);
  return a * b; }
static inline uint64_t exsi_mul_i(uint64_t a, uint64_t b, unsigned n)
{ uint64_t sa = a >> 63, sb = b >> 63;
  uint64_t ma = sa ? 0 - a : a, mb = sb ? 0 - b : b;   /* magnitudes; 2^63 stays 2^63 */
  uint64_t neg = sa ^ sb;
  uint64_t lim = neg ? UINT64_C(1) << (n - 1) : (UINT64_C(1) << (n - 1)) - 1;
  if (ma != 0 && mb > lim / ma) exsrt_abortus(1);
  { uint64_t p = ma * mb; return neg ? 0 - p : p; } }   /* canonical by construction */

/* div and rem -- spec 5.4 as decided 2026-09-25: the quotient TRUNCATED
 * TOWARD ZERO and the remainder's sign FOLLOWING THE DIVIDEND, so that
 * `a == (a/b)*b + (a rem b)` holds at every pair of signs. Both trap on a
 * zero divisor, and both trap on T_MIN / -1 -- `rem` included, whose
 * mathematical value there is 0: it is the remainder OF a division that
 * does not exist, and a `rem` answering 0 where its own `div` traps would
 * falsify the identity at the one pair of operands two instructions can
 * check it on. emit.inc's __bfa_emit_divrem argues the same two paragraphs
 * for the reference; these helpers are the same function, not a second
 * opinion about it.
 *
 * THE CHECKS PRECEDE THE DIVISION, where every other trapping helper above
 * checks after, and they have to for two independent reasons. The semantic
 * one: `rem`'s result carries no trace of the overflow (T_MIN rem -1 is 0,
 * a perfectly good value of T), so there is nothing to check afterwards.
 * The harness one: every fixture is compiled `-fsanitize=undefined
 * -fno-sanitize-recover=all`, so a helper that DIVIDED first would abort
 * inside UBSan -- wrong status, wrong text, exsrt_abortus never reached --
 * on precisely the two inputs whose trap is the thing being tested.
 *
 * T_MIN IS T'S OWN, NOT INT64_MIN. In `i8`, -128 / -1 is 128, which no
 * `i8` holds, and the 64-bit division of a sign-extended -128 by -1
 * computes it without a murmur; tests/ir/trap_div_minneg1.ir is that case
 * and nothing else. So the comparison is against -2^(N-1) for the operand
 * type's own N. At N = 64 the same line also stands in for the hardware's
 * divide error, which the reference likewise turns into kind 1 rather than
 * a second signal that depends on the width.
 *
 * NO SIGNED C DIVISION ANYWHERE. The signed pair divides MAGNITUDES and
 * puts the sign back, exactly as exsi_mul_i does, so the carrier's
 * implementation-defined uint64_t -> int64_t conversion is never needed
 * (this file relies on it nowhere but exsi_i64_from_bits, and then through
 * memcpy) and UBSan's signed-overflow check is never armed. `0 - x` on a
 * uint64_t is modular C, not overflow. The magnitude of T_MIN is 2^63,
 * which `0 - a` leaves as 2^63 -- still the right unsigned magnitude.
 *
 * NO NORMALISATION, and the proof rather than the habit. With a zero
 * divisor and T_MIN / -1 excluded the result is ALREADY a value of T:
 * |a/b| <= |a| for |b| >= 1, so the only out-of-range quotient is -T_MIN,
 * which is precisely the case just excluded; and |a rem b| < |b| <=
 * 2^(N-1), in range at every sign. `0 - q` on an in-range magnitude leaves
 * the value sign-extended, which is the canonical form (ssa-ir.md 2.2).
 *
 * n IS UNUSED IN THE UNSIGNED PAIR and the parameter still stays. A uN
 * quotient is at most the dividend and a uN remainder is less than the
 * divisor, so neither can leave the type, and unsigned division has no
 * T_MIN case to exclude -- but the emitter writes ONE call shape for every
 * row of the helper table, so the argument is passed and discarded the way
 * exsi_subs_u discards it. */
static inline uint64_t exsi_div_u(uint64_t a, uint64_t b, unsigned n)
{ (void)n; if (b == 0) exsrt_abortus(1); return a / b; }
static inline uint64_t exsi_rem_u(uint64_t a, uint64_t b, unsigned n)
{ (void)n; if (b == 0) exsrt_abortus(1); return a % b; }
static inline uint64_t exsi_div_i(uint64_t a, uint64_t b, unsigned n)
{ if (b == 0) exsrt_abortus(1);
  if (a == 0 - (UINT64_C(1) << (n - 1)) && b == UINT64_MAX) exsrt_abortus(1);
  { uint64_t sa = a >> 63, sb = b >> 63;
    uint64_t ma = sa ? 0 - a : a, mb = sb ? 0 - b : b;   /* magnitudes; 2^63 stays 2^63 */
    uint64_t q = ma / mb;
    return (sa ^ sb) ? 0 - q : q; } }                    /* canonical by construction */
static inline uint64_t exsi_rem_i(uint64_t a, uint64_t b, unsigned n)
{ if (b == 0) exsrt_abortus(1);
  if (a == 0 - (UINT64_C(1) << (n - 1)) && b == UINT64_MAX) exsrt_abortus(1);
  { uint64_t sa = a >> 63, sb = b >> 63;
    uint64_t ma = sa ? 0 - a : a, mb = sb ? 0 - b : b;
    uint64_t r = ma % mb;
    return sa ? 0 - r : r; } }                           /* the DIVIDEND's sign */

static inline uint64_t exsi_adds_u(uint64_t a, uint64_t b, unsigned n)
{ uint64_t t = a + b; return (n == 64 ? t < a : t > exsi_mask(n)) ? exsi_mask(n) : t; }
static inline uint64_t exsi_subs_u(uint64_t a, uint64_t b, unsigned n)
{ (void)n; return a < b ? 0 : a - b; }
static inline uint64_t exsi_adds_i(uint64_t a, uint64_t b, unsigned n)
{ uint64_t t = a + b, s = UINT64_C(1) << (n - 1);
  if (n == 64) return ((((a ^ t) & (b ^ t)) >> 63) != 0) ? ((a >> 63) ? s : s - 1) : t;
  return exsi_norm_i(t, n) != t ? ((t >> 63) ? exsi_norm_i(s, n) : s - 1) : t; }
static inline uint64_t exsi_subs_i(uint64_t a, uint64_t b, unsigned n)
{ uint64_t t = a - b, s = UINT64_C(1) << (n - 1);
  if (n == 64) return ((((a ^ b) & (a ^ t)) >> 63) != 0) ? ((a >> 63) ? s : s - 1) : t;
  return exsi_norm_i(t, n) != t ? ((t >> 63) ? exsi_norm_i(s, n) : s - 1) : t; }

/* A count >= the width traps, as spec 5.4 says it must ("traps, as + traps
 * on overflow"); after the check c < n <= 64, so every C shift below is
 * defined. A negative iN count is a huge unsigned and traps, which is what
 * the reference's `jae` does too. */
static inline uint64_t exsi_shl_u(uint64_t a, uint64_t c, unsigned n)
{ if (c >= n) exsrt_abortus(1); return exsi_norm_u(a << c, n); }
static inline uint64_t exsi_shl_i(uint64_t a, uint64_t c, unsigned n)
{ if (c >= n) exsrt_abortus(1); return exsi_norm_i(a << c, n); }
static inline uint64_t exsi_shr_u(uint64_t a, uint64_t c, unsigned n)
{ if (c >= n) exsrt_abortus(1); return a >> c; }
/* arithmetic right shift without a signed shift: the sign replicated by a
 * mask. c == 0 is split out because (x << 64) would be a shift by the
 * type's width. */
static inline uint64_t exsi_shr_i(uint64_t a, uint64_t c, unsigned n)
{ if (c >= n) exsrt_abortus(1);
  return c == 0 ? a : (a >> c) | ((0 - (a >> 63)) << (64 - c)); }

/* Byte-at-a-time, with explicit shifts: the emitted text depends on no
 * assumption about the C host's byte order and asserts none (c-backend.md
 * D2). p[i] is an unsigned char promoted to int and converted straight to
 * uint64_t by the | -- a value in 0..255, never operated on as an int. */
static inline uint64_t exsi_ld_be(const unsigned char *p, unsigned k)
{ uint64_t v = 0; unsigned i; for (i = 0; i < k; i++) v = (v << 8) | p[i]; return v; }
static inline uint64_t exsi_ld_le(const unsigned char *p, unsigned k)
{ uint64_t v = 0; unsigned i; for (i = 0; i < k; i++) v |= (uint64_t)p[i] << (8 * i); return v; }
static inline void exsi_st_be(unsigned char *p, unsigned k, uint64_t v)
{ unsigned i; for (i = 0; i < k; i++) p[i] = (unsigned char)(v >> (8 * (k - 1 - i))); }
static inline void exsi_st_le(unsigned char *p, unsigned k, uint64_t v)
{ unsigned i; for (i = 0; i < k; i++) p[i] = (unsigned char)(v >> (8 * i)); }
#if __BYTE_ORDER__ == __ORDER_LITTLE_ENDIAN__
# define exsi_ld_n exsi_ld_le
# define exsi_st_n exsi_st_le
#elif __BYTE_ORDER__ == __ORDER_BIG_ENDIAN__
# define exsi_ld_n exsi_ld_be
# define exsi_st_n exsi_st_be
#else
# error "exsecutor: unknown __BYTE_ORDER__"
#endif

_Static_assert(sizeof(void *) == 8, "exsecutor: this hospes has 64-bit addresses");

uint64_t exs_titulus_iudica(unsigned char *p0, uint64_t p1);
uint64_t exs_habet_regressum(unsigned char *p0, uint64_t p1);
uint64_t exs_proxima(unsigned char *p0, uint64_t p1, uint64_t p2);
uint64_t exs_finis(unsigned char *p0, uint64_t p1, uint64_t p2);
uint64_t exs_par(unsigned char *p0, uint64_t p1, uint64_t p2, unsigned char *p3, uint64_t p4, uint64_t p5);
uint64_t exs_subest(unsigned char *p0, uint64_t p1, unsigned char *p2, uint64_t p3);
uint64_t exs_tangit(unsigned char *p0, uint64_t p1, unsigned char *p2, uint64_t p3);
uint64_t exs_ancora(unsigned char *p0, uint64_t p1);
uint64_t exs_involucrum(uint64_t p0);
uint64_t exs_wx_cogitur(uint64_t p0, uint64_t p1);
uint64_t exs_wx_conceditur(uint64_t p0, uint64_t p1);

uint64_t exs_titulus_iudica(unsigned char *p0, uint64_t p1)
{
    unsigned char *v1;
    uint64_t v2;
    uint64_t v3;
    uint64_t v4;
    uint64_t v6;
    uint64_t v8;
    uint64_t v9;
    uint64_t v11;
    uint64_t v13;
    uint64_t v15;
    uint64_t v16;
    uint64_t v18;
    unsigned char *v20;
    uint64_t v21;
    uint64_t v22;
    uint64_t v23;
    uint64_t v24;
    uint64_t v26;
    uint64_t v27;
    uint64_t v29;
    uint64_t v32;
    uint64_t v33;
    uint64_t v35;
    uint64_t v36;
    uint64_t v38;
    uint64_t v41;
    uint64_t v42;
    uint64_t v44;
    uint64_t v45;
    uint64_t v47;
    uint64_t v50;
    uint64_t v51;
    uint64_t v53;
    uint64_t v55;
    uint64_t v56;
    uint64_t v58;
    uint64_t v60;
    uint64_t v61;
    uint64_t v62;
    uint64_t v63;
    uint64_t v64;
    uint64_t v65;
    uint64_t v66;
    uint64_t v67;
    uint64_t v68;
    uint64_t v69;
    uint64_t v71;
    uint64_t v74;
    uint64_t v75;
    uint64_t v77;
    uint64_t t15;
    uint64_t t60;
    uint64_t t61;
    uint64_t t62;
    uint64_t t63;
    uint64_t t64;
    uint64_t t65;
    uint64_t t66;
    uint64_t t67;
    v1 = p0;
    v2 = p1;
    v3 = UINT64_C(0);
    v4 = (v2 == v3);
    if (v4) {
        goto b2;
    } else {
        goto b3;
    }
b2:
    v6 = UINT64_C(1);
    return v6;
b3:
    v8 = UINT64_C(64);
    v9 = (v2 > v8);
    if (v9) {
        goto b4;
    } else {
        goto b5;
    }
b4:
    v11 = UINT64_C(2);
    return v11;
b5:
    v13 = UINT64_C(0);
    t15 = v13;
    v15 = t15;
    goto b6;
b6:
    v16 = (v15 < v2);
    if (v16) {
        goto b7;
    } else {
        goto b8;
    }
b7:
    v18 = UINT64_C(64);
    if (v15 >= v18) exsrt_abortus(1);
    v20 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v15 * 1);
    v21 = exsi_norm_u(exsi_ld_n(v20 + 0, 1), 8);
    v22 = UINT64_C(0);
    v23 = UINT64_C(48);
    v24 = (v21 >= v23);
    if (v24) {
        goto b10;
    } else {
        t64 = v22;
        v64 = t64;
        goto b11;
    }
b8:
    v77 = UINT64_C(0);
    return v77;
b9:
    v74 = UINT64_C(1);
    v75 = v15 + v74;
    t15 = v75;
    v15 = t15;
    goto b6;
b10:
    v26 = UINT64_C(57);
    v27 = (v21 <= v26);
    if (v27) {
        goto b12;
    } else {
        t65 = v22;
        v65 = t65;
        goto b13;
    }
b11:
    v32 = UINT64_C(65);
    v33 = (v21 >= v32);
    if (v33) {
        goto b14;
    } else {
        t63 = v64;
        v63 = t63;
        goto b15;
    }
b12:
    v29 = UINT64_C(1);
    t65 = v29;
    v65 = t65;
    goto b13;
b13:
    t64 = v65;
    v64 = t64;
    goto b11;
b14:
    v35 = UINT64_C(90);
    v36 = (v21 <= v35);
    if (v36) {
        goto b16;
    } else {
        t66 = v64;
        v66 = t66;
        goto b17;
    }
b15:
    v41 = UINT64_C(97);
    v42 = (v21 >= v41);
    if (v42) {
        goto b18;
    } else {
        t62 = v63;
        v62 = t62;
        goto b19;
    }
b16:
    v38 = UINT64_C(1);
    t66 = v38;
    v66 = t66;
    goto b17;
b17:
    t63 = v66;
    v63 = t63;
    goto b15;
b18:
    v44 = UINT64_C(122);
    v45 = (v21 <= v44);
    if (v45) {
        goto b20;
    } else {
        t67 = v63;
        v67 = t67;
        goto b21;
    }
b19:
    v50 = UINT64_C(45);
    v51 = (v21 == v50);
    if (v51) {
        goto b22;
    } else {
        t61 = v62;
        v61 = t61;
        goto b23;
    }
b20:
    v47 = UINT64_C(1);
    t67 = v47;
    v67 = t67;
    goto b21;
b21:
    t62 = v67;
    v62 = t62;
    goto b19;
b22:
    v53 = UINT64_C(1);
    t61 = v53;
    v61 = t61;
    goto b23;
b23:
    v55 = UINT64_C(95);
    v56 = (v21 == v55);
    if (v56) {
        goto b24;
    } else {
        t60 = v61;
        v60 = t60;
        goto b25;
    }
b24:
    v58 = UINT64_C(1);
    t60 = v58;
    v60 = t60;
    goto b25;
b25:
    v68 = UINT64_C(0);
    v69 = (v60 == v68);
    if (v69) {
        goto b26;
    } else {
        goto b27;
    }
b26:
    v71 = UINT64_C(3);
    return v71;
b27:
    goto b9;
}

uint64_t exs_habet_regressum(unsigned char *p0, uint64_t p1)
{
    unsigned char *v1;
    uint64_t v2;
    uint64_t v3;
    uint64_t v4;
    uint64_t v6;
    uint64_t v8;
    uint64_t v9;
    uint64_t v10;
    uint64_t v11;
    uint64_t v13;
    uint64_t v14;
    uint64_t v16;
    uint64_t v17;
    uint64_t v19;
    uint64_t v21;
    unsigned char *v23;
    uint64_t v24;
    uint64_t v25;
    uint64_t v26;
    uint64_t v28;
    uint64_t v31;
    uint64_t v32;
    uint64_t v33;
    uint64_t v34;
    uint64_t v36;
    uint64_t v37;
    uint64_t v38;
    uint64_t v39;
    uint64_t v41;
    unsigned char *v43;
    uint64_t v44;
    uint64_t v45;
    uint64_t v46;
    uint64_t v48;
    uint64_t v49;
    uint64_t v50;
    unsigned char *v52;
    uint64_t v53;
    uint64_t v54;
    uint64_t v55;
    uint64_t v57;
    uint64_t v61;
    uint64_t v62;
    uint64_t v65;
    uint64_t v66;
    uint64_t v68;
    uint64_t v69;
    uint64_t t13;
    uint64_t t31;
    uint64_t t32;
    uint64_t t36;
    uint64_t t68;
    v1 = p0;
    v2 = p1;
    v3 = UINT64_C(4096);
    v4 = (v2 > v3);
    if (v4) {
        goto b2;
    } else {
        goto b3;
    }
b2:
    v6 = UINT64_C(1);
    return v6;
b3:
    v8 = UINT64_C(0);
    v9 = UINT64_C(0);
    v10 = UINT64_C(1);
    v11 = exsi_add_u(v2, v10, 64);
    t36 = v8;
    t13 = v9;
    v36 = t36;
    v13 = t13;
    goto b4;
b4:
    v14 = (v13 < v11);
    if (v14) {
        goto b5;
    } else {
        goto b6;
    }
b5:
    v16 = UINT64_C(0);
    v17 = (v13 == v2);
    if (v17) {
        goto b8;
    } else {
        goto b9;
    }
b6:
    v69 = UINT64_C(0);
    return v69;
b7:
    v65 = UINT64_C(1);
    v66 = v13 + v65;
    t36 = v68;
    t13 = v66;
    v36 = t36;
    v13 = t13;
    goto b4;
b8:
    v19 = UINT64_C(1);
    t31 = v19;
    v31 = t31;
    goto b10;
b9:
    v21 = UINT64_C(4096);
    if (v13 >= v21) exsrt_abortus(1);
    v23 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v13 * 1);
    v24 = exsi_norm_u(exsi_ld_n(v23 + 0, 1), 8);
    v25 = UINT64_C(47);
    v26 = (v24 == v25);
    if (v26) {
        goto b11;
    } else {
        t32 = v16;
        v32 = t32;
        goto b12;
    }
b10:
    v33 = UINT64_C(1);
    v34 = (v31 == v33);
    if (v34) {
        goto b13;
    } else {
        t68 = v36;
        v68 = t68;
        goto b14;
    }
b11:
    v28 = UINT64_C(1);
    t32 = v28;
    v32 = t32;
    goto b12;
b12:
    t31 = v32;
    v31 = t31;
    goto b10;
b13:
    v37 = exsi_sub_u(v13, v36, 64);
    v38 = UINT64_C(2);
    v39 = (v37 == v38);
    if (v39) {
        goto b15;
    } else {
        goto b16;
    }
b14:
    goto b7;
b15:
    v41 = UINT64_C(4096);
    if (v36 >= v41) exsrt_abortus(1);
    v43 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v36 * 1);
    v44 = exsi_norm_u(exsi_ld_n(v43 + 0, 1), 8);
    v45 = UINT64_C(46);
    v46 = (v44 == v45);
    if (v46) {
        goto b17;
    } else {
        goto b18;
    }
b16:
    v61 = UINT64_C(1);
    v62 = exsi_add_u(v13, v61, 64);
    t68 = v62;
    v68 = t68;
    goto b14;
b17:
    v48 = UINT64_C(1);
    v49 = exsi_add_u(v36, v48, 64);
    v50 = UINT64_C(4096);
    if (v49 >= v50) exsrt_abortus(1);
    v52 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v49 * 1);
    v53 = exsi_norm_u(exsi_ld_n(v52 + 0, 1), 8);
    v54 = UINT64_C(46);
    v55 = (v53 == v54);
    if (v55) {
        goto b19;
    } else {
        goto b20;
    }
b18:
    goto b16;
b19:
    v57 = UINT64_C(1);
    return v57;
b20:
    goto b18;
}

uint64_t exs_proxima(unsigned char *p0, uint64_t p1, uint64_t p2)
{
    unsigned char *v1;
    uint64_t v2;
    uint64_t v3;
    uint64_t v4;
    uint64_t v5;
    uint64_t v6;
    uint64_t v8;
    uint64_t v9;
    uint64_t v11;
    uint64_t v12;
    uint64_t v13;
    uint64_t v15;
    uint64_t v16;
    uint64_t v18;
    uint64_t v20;
    unsigned char *v22;
    uint64_t v23;
    uint64_t v24;
    uint64_t v25;
    uint64_t v27;
    uint64_t v30;
    uint64_t v31;
    uint64_t v32;
    uint64_t v33;
    uint64_t v35;
    uint64_t v36;
    uint64_t v37;
    uint64_t v38;
    uint64_t v39;
    uint64_t v41;
    uint64_t v43;
    uint64_t v44;
    uint64_t v45;
    uint64_t v47;
    unsigned char *v49;
    uint64_t v50;
    uint64_t v51;
    uint64_t v52;
    uint64_t v54;
    uint64_t v57;
    uint64_t v58;
    uint64_t v59;
    uint64_t v60;
    uint64_t v61;
    uint64_t v63;
    uint64_t v65;
    uint64_t v66;
    uint64_t v70;
    uint64_t v71;
    uint64_t v73;
    uint64_t v74;
    uint64_t v75;
    uint64_t v76;
    uint64_t v77;
    uint64_t v78;
    uint64_t v79;
    uint64_t v80;
    uint64_t v81;
    uint64_t t8;
    uint64_t t11;
    uint64_t t30;
    uint64_t t31;
    uint64_t t36;
    uint64_t t57;
    uint64_t t58;
    uint64_t t59;
    uint64_t t73;
    uint64_t t74;
    uint64_t t75;
    uint64_t t76;
    uint64_t t77;
    uint64_t t78;
    uint64_t t79;
    uint64_t t80;
    uint64_t t81;
    v1 = p0;
    v2 = p1;
    v3 = p2;
    v4 = UINT64_C(0);
    v5 = UINT64_C(1);
    v6 = exsi_add_u(v2, v5, 64);
    t78 = v2;
    t36 = v3;
    t11 = v4;
    t8 = v3;
    v78 = t78;
    v36 = t36;
    v11 = t11;
    v8 = t8;
    goto b2;
b2:
    v9 = (v8 < v6);
    if (v9) {
        goto b3;
    } else {
        goto b4;
    }
b3:
    v12 = UINT64_C(0);
    v13 = (v11 == v12);
    if (v13) {
        goto b6;
    } else {
        t79 = v78;
        t76 = v36;
        t73 = v11;
        v79 = t79;
        v76 = t76;
        v73 = t73;
        goto b7;
    }
b4:
    return v78;
b5:
    v70 = UINT64_C(1);
    v71 = v8 + v70;
    t78 = v79;
    t36 = v76;
    t11 = v73;
    t8 = v71;
    v78 = t78;
    v36 = t36;
    v11 = t11;
    v8 = t8;
    goto b2;
b6:
    v15 = UINT64_C(0);
    v16 = (v8 == v2);
    if (v16) {
        goto b8;
    } else {
        goto b9;
    }
b7:
    goto b5;
b8:
    v18 = UINT64_C(1);
    t30 = v18;
    v30 = t30;
    goto b10;
b9:
    v20 = UINT64_C(4096);
    if (v8 >= v20) exsrt_abortus(1);
    v22 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v8 * 1);
    v23 = exsi_norm_u(exsi_ld_n(v22 + 0, 1), 8);
    v24 = UINT64_C(47);
    v25 = (v23 == v24);
    if (v25) {
        goto b11;
    } else {
        t31 = v15;
        v31 = t31;
        goto b12;
    }
b10:
    v32 = UINT64_C(1);
    v33 = (v30 == v32);
    if (v33) {
        goto b13;
    } else {
        t80 = v78;
        t77 = v36;
        t74 = v11;
        v80 = t80;
        v77 = t77;
        v74 = t74;
        goto b14;
    }
b11:
    v27 = UINT64_C(1);
    t31 = v27;
    v31 = t31;
    goto b12;
b12:
    t30 = v31;
    v30 = t30;
    goto b10;
b13:
    v35 = UINT64_C(0);
    v37 = exsi_sub_u(v8, v36, 64);
    v38 = UINT64_C(0);
    v39 = (v37 == v38);
    if (v39) {
        goto b15;
    } else {
        t58 = v35;
        v58 = t58;
        goto b16;
    }
b14:
    t79 = v80;
    t76 = v77;
    t73 = v74;
    v79 = t79;
    v76 = t76;
    v73 = t73;
    goto b7;
b15:
    v41 = UINT64_C(1);
    t58 = v41;
    v58 = t58;
    goto b16;
b16:
    v43 = exsi_sub_u(v8, v36, 64);
    v44 = UINT64_C(1);
    v45 = (v43 == v44);
    if (v45) {
        goto b17;
    } else {
        t57 = v58;
        v57 = t57;
        goto b18;
    }
b17:
    v47 = UINT64_C(4096);
    if (v36 >= v47) exsrt_abortus(1);
    v49 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v36 * 1);
    v50 = exsi_norm_u(exsi_ld_n(v49 + 0, 1), 8);
    v51 = UINT64_C(46);
    v52 = (v50 == v51);
    if (v52) {
        goto b19;
    } else {
        t59 = v58;
        v59 = t59;
        goto b20;
    }
b18:
    v60 = UINT64_C(0);
    v61 = (v57 == v60);
    if (v61) {
        goto b21;
    } else {
        t81 = v78;
        t75 = v11;
        v81 = t81;
        v75 = t75;
        goto b22;
    }
b19:
    v54 = UINT64_C(1);
    t59 = v54;
    v59 = t59;
    goto b20;
b20:
    t57 = v59;
    v57 = t57;
    goto b18;
b21:
    v63 = UINT64_C(1);
    t81 = v36;
    t75 = v63;
    v81 = t81;
    v75 = t75;
    goto b22;
b22:
    v65 = UINT64_C(1);
    v66 = exsi_add_u(v8, v65, 64);
    t80 = v81;
    t77 = v66;
    t74 = v75;
    v80 = t80;
    v77 = t77;
    v74 = t74;
    goto b14;
}

uint64_t exs_finis(unsigned char *p0, uint64_t p1, uint64_t p2)
{
    unsigned char *v1;
    uint64_t v2;
    uint64_t v3;
    uint64_t v4;
    uint64_t v6;
    uint64_t v7;
    uint64_t v9;
    uint64_t v10;
    uint64_t v11;
    uint64_t v13;
    unsigned char *v15;
    uint64_t v16;
    uint64_t v17;
    uint64_t v18;
    uint64_t v20;
    uint64_t v24;
    uint64_t v25;
    uint64_t v27;
    uint64_t v28;
    uint64_t v29;
    uint64_t v30;
    uint64_t v31;
    uint64_t t6;
    uint64_t t9;
    uint64_t t27;
    uint64_t t28;
    uint64_t t29;
    uint64_t t30;
    uint64_t t31;
    v1 = p0;
    v2 = p1;
    v3 = p2;
    v4 = UINT64_C(0);
    t29 = v2;
    t9 = v4;
    t6 = v3;
    v29 = t29;
    v9 = t9;
    v6 = t6;
    goto b2;
b2:
    v7 = (v6 < v2);
    if (v7) {
        goto b3;
    } else {
        goto b4;
    }
b3:
    v10 = UINT64_C(0);
    v11 = (v9 == v10);
    if (v11) {
        goto b6;
    } else {
        t30 = v29;
        t27 = v9;
        v30 = t30;
        v27 = t27;
        goto b7;
    }
b4:
    return v29;
b5:
    v24 = UINT64_C(1);
    v25 = v6 + v24;
    t29 = v30;
    t9 = v27;
    t6 = v25;
    v29 = t29;
    v9 = t9;
    v6 = t6;
    goto b2;
b6:
    v13 = UINT64_C(4096);
    if (v6 >= v13) exsrt_abortus(1);
    v15 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v6 * 1);
    v16 = exsi_norm_u(exsi_ld_n(v15 + 0, 1), 8);
    v17 = UINT64_C(47);
    v18 = (v16 == v17);
    if (v18) {
        goto b8;
    } else {
        t31 = v29;
        t28 = v9;
        v31 = t31;
        v28 = t28;
        goto b9;
    }
b7:
    goto b5;
b8:
    v20 = UINT64_C(1);
    t31 = v6;
    t28 = v20;
    v31 = t31;
    v28 = t28;
    goto b9;
b9:
    t30 = v31;
    t27 = v28;
    v30 = t30;
    v27 = t27;
    goto b7;
}

uint64_t exs_par(unsigned char *p0, uint64_t p1, uint64_t p2, unsigned char *p3, uint64_t p4, uint64_t p5)
{
    unsigned char *v1;
    uint64_t v2;
    uint64_t v3;
    unsigned char *v4;
    uint64_t v5;
    uint64_t v6;
    uint64_t v7;
    uint64_t v8;
    uint64_t v9;
    uint64_t v11;
    uint64_t v13;
    uint64_t v14;
    uint64_t v16;
    uint64_t v17;
    uint64_t v19;
    uint64_t v20;
    unsigned char *v22;
    uint64_t v23;
    uint64_t v24;
    uint64_t v25;
    unsigned char *v27;
    uint64_t v28;
    uint64_t v29;
    uint64_t v31;
    uint64_t v34;
    uint64_t v35;
    uint64_t v37;
    uint64_t t16;
    v1 = p0;
    v2 = p1;
    v3 = p2;
    v4 = p3;
    v5 = p4;
    v6 = p5;
    v7 = exsi_sub_u(v3, v2, 64);
    v8 = exsi_sub_u(v6, v5, 64);
    v9 = (v7 != v8);
    if (v9) {
        goto b2;
    } else {
        goto b3;
    }
b2:
    v11 = UINT64_C(0);
    return v11;
b3:
    v13 = UINT64_C(0);
    v14 = exsi_sub_u(v3, v2, 64);
    t16 = v13;
    v16 = t16;
    goto b4;
b4:
    v17 = (v16 < v14);
    if (v17) {
        goto b5;
    } else {
        goto b6;
    }
b5:
    v19 = exsi_add_u(v2, v16, 64);
    v20 = UINT64_C(4096);
    if (v19 >= v20) exsrt_abortus(1);
    v22 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v19 * 1);
    v23 = exsi_norm_u(exsi_ld_n(v22 + 0, 1), 8);
    v24 = exsi_add_u(v5, v16, 64);
    v25 = UINT64_C(4096);
    if (v24 >= v25) exsrt_abortus(1);
    v27 = (unsigned char *)((uintptr_t)v4 + (uintptr_t)v24 * 1);
    v28 = exsi_norm_u(exsi_ld_n(v27 + 0, 1), 8);
    v29 = (v23 != v28);
    if (v29) {
        goto b8;
    } else {
        goto b9;
    }
b6:
    v37 = UINT64_C(1);
    return v37;
b7:
    v34 = UINT64_C(1);
    v35 = v16 + v34;
    t16 = v35;
    v16 = t16;
    goto b4;
b8:
    v31 = UINT64_C(0);
    return v31;
b9:
    goto b7;
}

uint64_t exs_subest(unsigned char *p0, uint64_t p1, unsigned char *p2, uint64_t p3)
{
    unsigned char *v1;
    uint64_t v2;
    unsigned char *v3;
    uint64_t v4;
    uint64_t v5;
    uint64_t v6;
    uint64_t v8;
    uint64_t v10;
    uint64_t v11;
    uint64_t v13;
    uint64_t v15;
    uint64_t v16;
    uint64_t v17;
    uint64_t v19;
    uint64_t v21;
    uint64_t v22;
    uint64_t v24;
    uint64_t v26;
    uint64_t v27;
    unsigned char *v29;
    uint64_t v30;
    uint64_t v31;
    uint64_t v32;
    uint64_t v34;
    uint64_t v35;
    unsigned char *v37;
    uint64_t v38;
    uint64_t v39;
    uint64_t v40;
    uint64_t v42;
    uint64_t v45;
    uint64_t v46;
    uint64_t v48;
    uint64_t v50;
    uint64_t v51;
    unsigned char *v53;
    uint64_t v54;
    uint64_t v55;
    uint64_t v56;
    uint64_t v58;
    uint64_t v59;
    unsigned char *v61;
    uint64_t v62;
    uint64_t v63;
    uint64_t v64;
    uint64_t v66;
    uint64_t v69;
    uint64_t v70;
    unsigned char *v72;
    uint64_t v73;
    uint64_t v74;
    uint64_t v75;
    uint64_t v77;
    uint64_t v78;
    uint64_t v80;
    uint64_t v82;
    uint64_t v83;
    unsigned char *v85;
    uint64_t v86;
    uint64_t v87;
    uint64_t v88;
    uint64_t v90;
    uint64_t v93;
    uint64_t v94;
    unsigned char *v96;
    uint64_t v97;
    uint64_t v98;
    uint64_t v99;
    uint64_t v101;
    uint64_t v104;
    uint64_t v105;
    uint64_t v106;
    uint64_t v107;
    uint64_t v108;
    uint64_t v109;
    uint64_t v111;
    uint64_t v112;
    uint64_t v114;
    uint64_t v115;
    uint64_t v116;
    uint64_t v118;
    uint64_t v119;
    uint64_t v120;
    uint64_t v122;
    uint64_t v124;
    uint64_t v125;
    uint64_t v126;
    uint64_t v127;
    uint64_t v129;
    unsigned char *v131;
    uint64_t v132;
    uint64_t v133;
    uint64_t v134;
    uint64_t v136;
    uint64_t v137;
    uint64_t v138;
    unsigned char *v140;
    uint64_t v141;
    uint64_t v142;
    uint64_t v143;
    uint64_t v145;
    uint64_t v149;
    uint64_t v150;
    uint64_t v151;
    uint64_t v153;
    uint64_t v155;
    uint64_t v156;
    uint64_t v157;
    uint64_t v158;
    uint64_t v160;
    uint64_t v165;
    uint64_t v166;
    uint64_t v168;
    uint64_t v169;
    uint64_t v170;
    uint64_t v171;
    uint64_t v172;
    uint64_t v173;
    uint64_t v174;
    uint64_t t111;
    uint64_t t114;
    uint64_t t118;
    uint64_t t149;
    uint64_t t168;
    uint64_t t169;
    uint64_t t170;
    uint64_t t171;
    uint64_t t172;
    uint64_t t173;
    v1 = p0;
    v2 = p1;
    v3 = p2;
    v4 = p3;
    v5 = UINT64_C(4096);
    v6 = (v2 > v5);
    if (v6) {
        goto b2;
    } else {
        goto b3;
    }
b2:
    v8 = UINT64_C(1);
    return v8;
b3:
    v10 = UINT64_C(4096);
    v11 = (v4 > v10);
    if (v11) {
        goto b4;
    } else {
        goto b5;
    }
b4:
    v13 = UINT64_C(1);
    return v13;
b5:
    v15 = exs_habet_regressum(v1, v2);
    v16 = UINT64_C(1);
    v17 = (v15 == v16);
    if (v17) {
        goto b6;
    } else {
        goto b7;
    }
b6:
    v19 = UINT64_C(1);
    return v19;
b7:
    v21 = UINT64_C(0);
    v22 = (v2 == v21);
    if (v22) {
        goto b8;
    } else {
        goto b9;
    }
b8:
    v24 = UINT64_C(1);
    return v24;
b9:
    v26 = UINT64_C(0);
    v27 = UINT64_C(4096);
    if (v26 >= v27) exsrt_abortus(1);
    v29 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v26 * 1);
    v30 = exsi_norm_u(exsi_ld_n(v29 + 0, 1), 8);
    v31 = UINT64_C(47);
    v32 = (v30 != v31);
    if (v32) {
        goto b10;
    } else {
        goto b11;
    }
b10:
    v34 = UINT64_C(0);
    v35 = UINT64_C(4096);
    if (v34 >= v35) exsrt_abortus(1);
    v37 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v34 * 1);
    v38 = exsi_norm_u(exsi_ld_n(v37 + 0, 1), 8);
    v39 = UINT64_C(36);
    v40 = (v38 != v39);
    if (v40) {
        goto b12;
    } else {
        goto b13;
    }
b11:
    v45 = UINT64_C(0);
    v46 = (v4 == v45);
    if (v46) {
        goto b14;
    } else {
        goto b15;
    }
b12:
    v42 = UINT64_C(1);
    return v42;
b13:
    goto b11;
b14:
    v48 = UINT64_C(1);
    return v48;
b15:
    v50 = UINT64_C(0);
    v51 = UINT64_C(4096);
    if (v50 >= v51) exsrt_abortus(1);
    v53 = (unsigned char *)((uintptr_t)v3 + (uintptr_t)v50 * 1);
    v54 = exsi_norm_u(exsi_ld_n(v53 + 0, 1), 8);
    v55 = UINT64_C(47);
    v56 = (v54 == v55);
    if (v56) {
        goto b16;
    } else {
        goto b17;
    }
b16:
    v58 = UINT64_C(0);
    v59 = UINT64_C(4096);
    if (v58 >= v59) exsrt_abortus(1);
    v61 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v58 * 1);
    v62 = exsi_norm_u(exsi_ld_n(v61 + 0, 1), 8);
    v63 = UINT64_C(47);
    v64 = (v62 != v63);
    if (v64) {
        goto b18;
    } else {
        goto b19;
    }
b17:
    v69 = UINT64_C(0);
    v70 = UINT64_C(4096);
    if (v69 >= v70) exsrt_abortus(1);
    v72 = (unsigned char *)((uintptr_t)v3 + (uintptr_t)v69 * 1);
    v73 = exsi_norm_u(exsi_ld_n(v72 + 0, 1), 8);
    v74 = UINT64_C(46);
    v75 = (v73 == v74);
    if (v75) {
        goto b21;
    } else {
        goto b22;
    }
b18:
    v66 = UINT64_C(0);
    return v66;
b19:
    goto b20;
b20:
    v104 = UINT64_C(0);
    v105 = UINT64_C(0);
    v106 = UINT64_C(1);
    v107 = UINT64_C(0);
    v108 = UINT64_C(1);
    v109 = exsi_add_u(v4, v108, 64);
    t149 = v105;
    t118 = v104;
    t114 = v106;
    t111 = v107;
    v149 = t149;
    v118 = t118;
    v114 = t114;
    v111 = t111;
    goto b29;
b21:
    v77 = UINT64_C(1);
    v78 = (v4 == v77);
    if (v78) {
        goto b23;
    } else {
        goto b24;
    }
b22:
    v93 = UINT64_C(0);
    v94 = UINT64_C(4096);
    if (v93 >= v94) exsrt_abortus(1);
    v96 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v93 * 1);
    v97 = exsi_norm_u(exsi_ld_n(v96 + 0, 1), 8);
    v98 = UINT64_C(47);
    v99 = (v97 == v98);
    if (v99) {
        goto b27;
    } else {
        goto b28;
    }
b23:
    v80 = UINT64_C(0);
    return v80;
b24:
    v82 = UINT64_C(1);
    v83 = UINT64_C(4096);
    if (v82 >= v83) exsrt_abortus(1);
    v85 = (unsigned char *)((uintptr_t)v3 + (uintptr_t)v82 * 1);
    v86 = exsi_norm_u(exsi_ld_n(v85 + 0, 1), 8);
    v87 = UINT64_C(47);
    v88 = (v86 == v87);
    if (v88) {
        goto b25;
    } else {
        goto b26;
    }
b25:
    v90 = UINT64_C(0);
    return v90;
b26:
    goto b22;
b27:
    v101 = UINT64_C(0);
    return v101;
b28:
    goto b20;
b29:
    v112 = (v111 < v109);
    if (v112) {
        goto b30;
    } else {
        goto b31;
    }
b30:
    v115 = UINT64_C(1);
    v116 = (v114 == v115);
    if (v116) {
        goto b33;
    } else {
        t172 = v149;
        t170 = v118;
        t168 = v114;
        v172 = t172;
        v170 = t170;
        v168 = t168;
        goto b34;
    }
b31:
    v174 = UINT64_C(1);
    return v174;
b32:
    v165 = UINT64_C(1);
    v166 = v111 + v165;
    t149 = v172;
    t118 = v170;
    t114 = v168;
    t111 = v166;
    v149 = t149;
    v118 = t118;
    v114 = t114;
    v111 = t111;
    goto b29;
b33:
    v119 = exs_proxima(v3, v4, v118);
    v120 = (v119 == v4);
    if (v120) {
        goto b35;
    } else {
        goto b36;
    }
b34:
    goto b32;
b35:
    v122 = UINT64_C(0);
    t173 = v149;
    t171 = v118;
    t169 = v122;
    v173 = t173;
    v171 = t171;
    v169 = t169;
    goto b37;
b36:
    v124 = exs_finis(v3, v4, v119);
    v125 = exsi_sub_u(v124, v119, 64);
    v126 = UINT64_C(2);
    v127 = (v125 == v126);
    if (v127) {
        goto b38;
    } else {
        goto b39;
    }
b37:
    t172 = v173;
    t170 = v171;
    t168 = v169;
    v172 = t172;
    v170 = t170;
    v168 = t168;
    goto b34;
b38:
    v129 = UINT64_C(4096);
    if (v119 >= v129) exsrt_abortus(1);
    v131 = (unsigned char *)((uintptr_t)v3 + (uintptr_t)v119 * 1);
    v132 = exsi_norm_u(exsi_ld_n(v131 + 0, 1), 8);
    v133 = UINT64_C(46);
    v134 = (v132 == v133);
    if (v134) {
        goto b40;
    } else {
        goto b41;
    }
b39:
    v150 = exs_proxima(v1, v2, v149);
    v151 = (v150 == v2);
    if (v151) {
        goto b44;
    } else {
        goto b45;
    }
b40:
    v136 = UINT64_C(1);
    v137 = exsi_add_u(v119, v136, 64);
    v138 = UINT64_C(4096);
    if (v137 >= v138) exsrt_abortus(1);
    v140 = (unsigned char *)((uintptr_t)v3 + (uintptr_t)v137 * 1);
    v141 = exsi_norm_u(exsi_ld_n(v140 + 0, 1), 8);
    v142 = UINT64_C(46);
    v143 = (v141 == v142);
    if (v143) {
        goto b42;
    } else {
        goto b43;
    }
b41:
    goto b39;
b42:
    v145 = UINT64_C(0);
    return v145;
b43:
    goto b41;
b44:
    v153 = UINT64_C(0);
    return v153;
b45:
    v155 = exs_finis(v1, v2, v150);
    v156 = exs_par(v1, v150, v155, v3, v119, v124);
    v157 = UINT64_C(0);
    v158 = (v156 == v157);
    if (v158) {
        goto b46;
    } else {
        goto b47;
    }
b46:
    v160 = UINT64_C(0);
    return v160;
b47:
    t173 = v155;
    t171 = v124;
    t169 = v114;
    v173 = t173;
    v171 = t171;
    v169 = t169;
    goto b37;
}

uint64_t exs_tangit(unsigned char *p0, uint64_t p1, unsigned char *p2, uint64_t p3)
{
    unsigned char *v1;
    uint64_t v2;
    unsigned char *v3;
    uint64_t v4;
    uint64_t v5;
    uint64_t v6;
    uint64_t v8;
    uint64_t v10;
    uint64_t v11;
    uint64_t v13;
    uint64_t v15;
    uint64_t v16;
    uint64_t v17;
    uint64_t v19;
    uint64_t v21;
    uint64_t v22;
    uint64_t v24;
    uint64_t v25;
    unsigned char *v27;
    uint64_t v28;
    uint64_t v29;
    uint64_t v30;
    uint64_t v32;
    uint64_t v33;
    uint64_t v34;
    uint64_t v36;
    uint64_t v40;
    v1 = p0;
    v2 = p1;
    v3 = p2;
    v4 = p3;
    v5 = UINT64_C(4096);
    v6 = (v2 > v5);
    if (v6) {
        goto b2;
    } else {
        goto b3;
    }
b2:
    v8 = UINT64_C(3);
    return v8;
b3:
    v10 = UINT64_C(4096);
    v11 = (v4 > v10);
    if (v11) {
        goto b4;
    } else {
        goto b5;
    }
b4:
    v13 = UINT64_C(3);
    return v13;
b5:
    v15 = exs_subest(v1, v2, v3, v4);
    v16 = UINT64_C(1);
    v17 = (v15 == v16);
    if (v17) {
        goto b6;
    } else {
        goto b7;
    }
b6:
    v19 = UINT64_C(1);
    return v19;
b7:
    v21 = UINT64_C(0);
    v22 = (v2 > v21);
    if (v22) {
        goto b8;
    } else {
        goto b9;
    }
b8:
    v24 = UINT64_C(0);
    v25 = UINT64_C(4096);
    if (v24 >= v25) exsrt_abortus(1);
    v27 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v24 * 1);
    v28 = exsi_norm_u(exsi_ld_n(v27 + 0, 1), 8);
    v29 = UINT64_C(47);
    v30 = (v28 == v29);
    if (v30) {
        goto b10;
    } else {
        goto b11;
    }
b9:
    v40 = UINT64_C(0);
    return v40;
b10:
    v32 = exs_subest(v3, v4, v1, v2);
    v33 = UINT64_C(1);
    v34 = (v32 == v33);
    if (v34) {
        goto b12;
    } else {
        goto b13;
    }
b11:
    goto b9;
b12:
    v36 = UINT64_C(2);
    return v36;
b13:
    goto b11;
}

uint64_t exs_ancora(unsigned char *p0, uint64_t p1)
{
    unsigned char *v1;
    uint64_t v2;
    uint64_t v3;
    uint64_t v4;
    uint64_t v6;
    uint64_t v8;
    uint64_t v9;
    uint64_t v11;
    uint64_t v13;
    uint64_t v14;
    unsigned char *v16;
    uint64_t v17;
    uint64_t v18;
    uint64_t v19;
    uint64_t v21;
    uint64_t v23;
    uint64_t v24;
    unsigned char *v26;
    uint64_t v27;
    uint64_t v28;
    uint64_t v29;
    uint64_t v31;
    uint64_t v33;
    uint64_t v34;
    uint64_t v36;
    uint64_t v37;
    unsigned char *v39;
    uint64_t v40;
    uint64_t v41;
    uint64_t v42;
    uint64_t v44;
    uint64_t v45;
    unsigned char *v47;
    uint64_t v48;
    uint64_t v49;
    uint64_t v50;
    uint64_t v52;
    uint64_t v53;
    unsigned char *v55;
    uint64_t v56;
    uint64_t v57;
    uint64_t v58;
    uint64_t v60;
    uint64_t v61;
    unsigned char *v63;
    uint64_t v64;
    uint64_t v65;
    uint64_t v66;
    uint64_t v68;
    uint64_t v69;
    unsigned char *v71;
    uint64_t v72;
    uint64_t v73;
    uint64_t v74;
    uint64_t v76;
    uint64_t v83;
    uint64_t v84;
    uint64_t v86;
    uint64_t v87;
    unsigned char *v89;
    uint64_t v90;
    uint64_t v91;
    uint64_t v92;
    uint64_t v94;
    uint64_t v95;
    unsigned char *v97;
    uint64_t v98;
    uint64_t v99;
    uint64_t v100;
    uint64_t v102;
    uint64_t v103;
    unsigned char *v105;
    uint64_t v106;
    uint64_t v107;
    uint64_t v108;
    uint64_t v110;
    uint64_t v111;
    unsigned char *v113;
    uint64_t v114;
    uint64_t v115;
    uint64_t v116;
    uint64_t v118;
    uint64_t v119;
    unsigned char *v121;
    uint64_t v122;
    uint64_t v123;
    uint64_t v124;
    uint64_t v126;
    uint64_t v127;
    unsigned char *v129;
    uint64_t v130;
    uint64_t v131;
    uint64_t v132;
    uint64_t v134;
    uint64_t v142;
    uint64_t v143;
    uint64_t v145;
    uint64_t v146;
    unsigned char *v148;
    uint64_t v149;
    uint64_t v150;
    uint64_t v151;
    uint64_t v153;
    uint64_t v154;
    unsigned char *v156;
    uint64_t v157;
    uint64_t v158;
    uint64_t v159;
    uint64_t v161;
    uint64_t v162;
    unsigned char *v164;
    uint64_t v165;
    uint64_t v166;
    uint64_t v167;
    uint64_t v169;
    uint64_t v170;
    unsigned char *v172;
    uint64_t v173;
    uint64_t v174;
    uint64_t v175;
    uint64_t v177;
    uint64_t v178;
    unsigned char *v180;
    uint64_t v181;
    uint64_t v182;
    uint64_t v183;
    uint64_t v185;
    uint64_t v192;
    v1 = p0;
    v2 = p1;
    v3 = UINT64_C(0);
    v4 = (v2 == v3);
    if (v4) {
        goto b2;
    } else {
        goto b3;
    }
b2:
    v6 = UINT64_C(0);
    return v6;
b3:
    v8 = UINT64_C(4096);
    v9 = (v2 > v8);
    if (v9) {
        goto b4;
    } else {
        goto b5;
    }
b4:
    v11 = UINT64_C(0);
    return v11;
b5:
    v13 = UINT64_C(0);
    v14 = UINT64_C(4096);
    if (v13 >= v14) exsrt_abortus(1);
    v16 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v13 * 1);
    v17 = exsi_norm_u(exsi_ld_n(v16 + 0, 1), 8);
    v18 = UINT64_C(47);
    v19 = (v17 == v18);
    if (v19) {
        goto b6;
    } else {
        goto b7;
    }
b6:
    v21 = UINT64_C(1);
    return v21;
b7:
    v23 = UINT64_C(0);
    v24 = UINT64_C(4096);
    if (v23 >= v24) exsrt_abortus(1);
    v26 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v23 * 1);
    v27 = exsi_norm_u(exsi_ld_n(v26 + 0, 1), 8);
    v28 = UINT64_C(36);
    v29 = (v27 != v28);
    if (v29) {
        goto b8;
    } else {
        goto b9;
    }
b8:
    v31 = UINT64_C(0);
    return v31;
b9:
    v33 = UINT64_C(6);
    v34 = (v2 >= v33);
    if (v34) {
        goto b10;
    } else {
        goto b11;
    }
b10:
    v36 = UINT64_C(1);
    v37 = UINT64_C(4096);
    if (v36 >= v37) exsrt_abortus(1);
    v39 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v36 * 1);
    v40 = exsi_norm_u(exsi_ld_n(v39 + 0, 1), 8);
    v41 = UINT64_C(83);
    v42 = (v40 == v41);
    if (v42) {
        goto b12;
    } else {
        goto b13;
    }
b11:
    v83 = UINT64_C(7);
    v84 = (v2 >= v83);
    if (v84) {
        goto b22;
    } else {
        goto b23;
    }
b12:
    v44 = UINT64_C(2);
    v45 = UINT64_C(4096);
    if (v44 >= v45) exsrt_abortus(1);
    v47 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v44 * 1);
    v48 = exsi_norm_u(exsi_ld_n(v47 + 0, 1), 8);
    v49 = UINT64_C(84);
    v50 = (v48 == v49);
    if (v50) {
        goto b14;
    } else {
        goto b15;
    }
b13:
    goto b11;
b14:
    v52 = UINT64_C(3);
    v53 = UINT64_C(4096);
    if (v52 >= v53) exsrt_abortus(1);
    v55 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v52 * 1);
    v56 = exsi_norm_u(exsi_ld_n(v55 + 0, 1), 8);
    v57 = UINT64_C(65);
    v58 = (v56 == v57);
    if (v58) {
        goto b16;
    } else {
        goto b17;
    }
b15:
    goto b13;
b16:
    v60 = UINT64_C(4);
    v61 = UINT64_C(4096);
    if (v60 >= v61) exsrt_abortus(1);
    v63 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v60 * 1);
    v64 = exsi_norm_u(exsi_ld_n(v63 + 0, 1), 8);
    v65 = UINT64_C(84);
    v66 = (v64 == v65);
    if (v66) {
        goto b18;
    } else {
        goto b19;
    }
b17:
    goto b15;
b18:
    v68 = UINT64_C(5);
    v69 = UINT64_C(4096);
    if (v68 >= v69) exsrt_abortus(1);
    v71 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v68 * 1);
    v72 = exsi_norm_u(exsi_ld_n(v71 + 0, 1), 8);
    v73 = UINT64_C(69);
    v74 = (v72 == v73);
    if (v74) {
        goto b20;
    } else {
        goto b21;
    }
b19:
    goto b17;
b20:
    v76 = UINT64_C(1);
    return v76;
b21:
    goto b19;
b22:
    v86 = UINT64_C(1);
    v87 = UINT64_C(4096);
    if (v86 >= v87) exsrt_abortus(1);
    v89 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v86 * 1);
    v90 = exsi_norm_u(exsi_ld_n(v89 + 0, 1), 8);
    v91 = UINT64_C(67);
    v92 = (v90 == v91);
    if (v92) {
        goto b24;
    } else {
        goto b25;
    }
b23:
    v142 = UINT64_C(6);
    v143 = (v2 >= v142);
    if (v143) {
        goto b36;
    } else {
        goto b37;
    }
b24:
    v94 = UINT64_C(2);
    v95 = UINT64_C(4096);
    if (v94 >= v95) exsrt_abortus(1);
    v97 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v94 * 1);
    v98 = exsi_norm_u(exsi_ld_n(v97 + 0, 1), 8);
    v99 = UINT64_C(79);
    v100 = (v98 == v99);
    if (v100) {
        goto b26;
    } else {
        goto b27;
    }
b25:
    goto b23;
b26:
    v102 = UINT64_C(3);
    v103 = UINT64_C(4096);
    if (v102 >= v103) exsrt_abortus(1);
    v105 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v102 * 1);
    v106 = exsi_norm_u(exsi_ld_n(v105 + 0, 1), 8);
    v107 = UINT64_C(78);
    v108 = (v106 == v107);
    if (v108) {
        goto b28;
    } else {
        goto b29;
    }
b27:
    goto b25;
b28:
    v110 = UINT64_C(4);
    v111 = UINT64_C(4096);
    if (v110 >= v111) exsrt_abortus(1);
    v113 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v110 * 1);
    v114 = exsi_norm_u(exsi_ld_n(v113 + 0, 1), 8);
    v115 = UINT64_C(70);
    v116 = (v114 == v115);
    if (v116) {
        goto b30;
    } else {
        goto b31;
    }
b29:
    goto b27;
b30:
    v118 = UINT64_C(5);
    v119 = UINT64_C(4096);
    if (v118 >= v119) exsrt_abortus(1);
    v121 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v118 * 1);
    v122 = exsi_norm_u(exsi_ld_n(v121 + 0, 1), 8);
    v123 = UINT64_C(73);
    v124 = (v122 == v123);
    if (v124) {
        goto b32;
    } else {
        goto b33;
    }
b31:
    goto b29;
b32:
    v126 = UINT64_C(6);
    v127 = UINT64_C(4096);
    if (v126 >= v127) exsrt_abortus(1);
    v129 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v126 * 1);
    v130 = exsi_norm_u(exsi_ld_n(v129 + 0, 1), 8);
    v131 = UINT64_C(71);
    v132 = (v130 == v131);
    if (v132) {
        goto b34;
    } else {
        goto b35;
    }
b33:
    goto b31;
b34:
    v134 = UINT64_C(1);
    return v134;
b35:
    goto b33;
b36:
    v145 = UINT64_C(1);
    v146 = UINT64_C(4096);
    if (v145 >= v146) exsrt_abortus(1);
    v148 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v145 * 1);
    v149 = exsi_norm_u(exsi_ld_n(v148 + 0, 1), 8);
    v150 = UINT64_C(83);
    v151 = (v149 == v150);
    if (v151) {
        goto b38;
    } else {
        goto b39;
    }
b37:
    v192 = UINT64_C(0);
    return v192;
b38:
    v153 = UINT64_C(2);
    v154 = UINT64_C(4096);
    if (v153 >= v154) exsrt_abortus(1);
    v156 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v153 * 1);
    v157 = exsi_norm_u(exsi_ld_n(v156 + 0, 1), 8);
    v158 = UINT64_C(84);
    v159 = (v157 == v158);
    if (v159) {
        goto b40;
    } else {
        goto b41;
    }
b39:
    goto b37;
b40:
    v161 = UINT64_C(3);
    v162 = UINT64_C(4096);
    if (v161 >= v162) exsrt_abortus(1);
    v164 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v161 * 1);
    v165 = exsi_norm_u(exsi_ld_n(v164 + 0, 1), 8);
    v166 = UINT64_C(79);
    v167 = (v165 == v166);
    if (v167) {
        goto b42;
    } else {
        goto b43;
    }
b41:
    goto b39;
b42:
    v169 = UINT64_C(4);
    v170 = UINT64_C(4096);
    if (v169 >= v170) exsrt_abortus(1);
    v172 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v169 * 1);
    v173 = exsi_norm_u(exsi_ld_n(v172 + 0, 1), 8);
    v174 = UINT64_C(82);
    v175 = (v173 == v174);
    if (v175) {
        goto b44;
    } else {
        goto b45;
    }
b43:
    goto b41;
b44:
    v177 = UINT64_C(5);
    v178 = UINT64_C(4096);
    if (v177 >= v178) exsrt_abortus(1);
    v180 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v177 * 1);
    v181 = exsi_norm_u(exsi_ld_n(v180 + 0, 1), 8);
    v182 = UINT64_C(69);
    v183 = (v181 == v182);
    if (v183) {
        goto b46;
    } else {
        goto b47;
    }
b45:
    goto b43;
b46:
    v185 = UINT64_C(1);
    return v185;
b47:
    goto b45;
}

uint64_t exs_involucrum(uint64_t p0)
{
    uint64_t v1;
    uint64_t v2;
    uint64_t v3;
    uint64_t v5;
    uint64_t v7;
    uint64_t v8;
    uint64_t v10;
    uint64_t v12;
    uint64_t v13;
    uint64_t v15;
    uint64_t v17;
    v1 = p0;
    v2 = UINT64_C(3);
    v3 = (v1 > v2);
    if (v3) {
        goto b2;
    } else {
        goto b3;
    }
b2:
    v5 = UINT64_C(2);
    return v5;
b3:
    v7 = UINT64_C(1);
    v8 = (v1 == v7);
    if (v8) {
        goto b4;
    } else {
        goto b5;
    }
b4:
    v10 = UINT64_C(1);
    return v10;
b5:
    v12 = UINT64_C(2);
    v13 = (v1 == v12);
    if (v13) {
        goto b6;
    } else {
        goto b7;
    }
b6:
    v15 = UINT64_C(1);
    return v15;
b7:
    v17 = UINT64_C(0);
    return v17;
}

uint64_t exs_wx_cogitur(uint64_t p0, uint64_t p1)
{
    uint64_t v1;
    uint64_t v2;
    uint64_t v3;
    uint64_t v4;
    uint64_t v6;
    uint64_t v8;
    uint64_t v9;
    uint64_t v11;
    uint64_t v13;
    uint64_t v14;
    uint64_t v16;
    uint64_t v18;
    uint64_t v19;
    uint64_t v21;
    uint64_t v23;
    uint64_t v24;
    uint64_t v26;
    uint64_t v28;
    v1 = p0;
    v2 = p1;
    v3 = UINT64_C(3);
    v4 = (v1 > v3);
    if (v4) {
        goto b2;
    } else {
        goto b3;
    }
b2:
    v6 = UINT64_C(2);
    return v6;
b3:
    v8 = UINT64_C(2);
    v9 = (v2 > v8);
    if (v9) {
        goto b4;
    } else {
        goto b5;
    }
b4:
    v11 = UINT64_C(2);
    return v11;
b5:
    v13 = UINT64_C(0);
    v14 = (v1 == v13);
    if (v14) {
        goto b6;
    } else {
        goto b7;
    }
b6:
    v16 = UINT64_C(0);
    return v16;
b7:
    v18 = UINT64_C(3);
    v19 = (v1 == v18);
    if (v19) {
        goto b8;
    } else {
        goto b9;
    }
b8:
    v21 = UINT64_C(1);
    return v21;
b9:
    v23 = UINT64_C(2);
    v24 = (v2 == v23);
    if (v24) {
        goto b10;
    } else {
        goto b11;
    }
b10:
    v26 = UINT64_C(0);
    return v26;
b11:
    v28 = UINT64_C(1);
    return v28;
}

uint64_t exs_wx_conceditur(uint64_t p0, uint64_t p1)
{
    uint64_t v1;
    uint64_t v2;
    uint64_t v3;
    uint64_t v4;
    uint64_t v6;
    uint64_t v8;
    uint64_t v9;
    uint64_t v11;
    uint64_t v13;
    uint64_t v14;
    uint64_t v16;
    uint64_t v18;
    v1 = p0;
    v2 = p1;
    v3 = UINT64_C(3);
    v4 = (v1 > v3);
    if (v4) {
        goto b2;
    } else {
        goto b3;
    }
b2:
    v6 = UINT64_C(2);
    return v6;
b3:
    v8 = UINT64_C(2);
    v9 = (v2 > v8);
    if (v9) {
        goto b4;
    } else {
        goto b5;
    }
b4:
    v11 = UINT64_C(2);
    return v11;
b5:
    v13 = UINT64_C(2);
    v14 = (v2 != v13);
    if (v14) {
        goto b6;
    } else {
        goto b7;
    }
b6:
    v16 = UINT64_C(0);
    return v16;
b7:
    v18 = exs_involucrum(v1);
    return v18;
}

